# -*- coding: utf-8 -*-
# Question banks for 12 new exam-focused K-12 science games.
# Each game: id, title, emoji, grades, topic, subject, desc, skills, difficulty,
# time, caPoints (NGSS), plus 3 levels of questions.
# Question shape (choice mode): {"q": "...", "choices": [...], "answer": 0, "sub": "hint", "why": "explanation shown on wrong"}
# answer is ALWAYS index 0 in the source; the engine shuffles choices at render.

GAMES = [
  # ───────────────────────── HIGH SCHOOL BIOLOGY ─────────────────────────
  {
    "id": "cell-organelle-rush", "title": "Cell Organelle Rush", "emoji": "🔬",
    "grades": "Gr 7-12", "topic": "Biology", "subject": "Science",
    "desc": "Race to match organelles to their jobs — the cell-biology facts exams love to test",
    "skills": ["cell biology", "organelles", "cell structure", "eukaryotes"],
    "difficulty": "medium", "time": 12, "caPoints": ["NGSS.HS-LS1-2", "NGSS.MS-LS1-2"],
    "palette": "bio",
    "levels": [
      [
        {"q":"Which organelle is the <b>powerhouse of the cell</b>?","choices":["Mitochondrion","Ribosome","Golgi apparatus","Lysosome"],"sub":"It makes ATP energy","why":"Mitochondria run cellular respiration to produce ATP."},
        {"q":"Where is <b>DNA</b> stored in a eukaryotic cell?","choices":["Nucleus","Cytoplasm","Cell membrane","Vacuole"],"sub":"The cell's control center","why":"The nucleus houses and protects the cell's DNA."},
        {"q":"Which organelle builds <b>proteins</b>?","choices":["Ribosome","Lysosome","Nucleolus","Chloroplast"],"sub":"Reads mRNA to assemble amino acids","why":"Ribosomes translate mRNA into polypeptide chains."},
        {"q":"What controls what enters and leaves the cell?","choices":["Cell membrane","Cell wall","Nucleus","Cytoskeleton"],"sub":"Selectively permeable barrier","why":"The plasma membrane regulates transport in and out."},
        {"q":"Which organelle captures light for <b>photosynthesis</b>?","choices":["Chloroplast","Mitochondrion","Vacuole","Golgi apparatus"],"sub":"Only in plants and algae","why":"Chloroplasts contain chlorophyll and run photosynthesis."},
      ],
      [
        {"q":"The <b>Golgi apparatus</b> mainly does what?","choices":["Packages and ships proteins","Makes ATP","Stores DNA","Digests waste"],"sub":"Cellular post office","why":"The Golgi modifies, sorts, and packages proteins for transport."},
        {"q":"Which organelle contains digestive <b>enzymes</b> to break down waste?","choices":["Lysosome","Ribosome","Nucleus","Chloroplast"],"sub":"The cell's recycling center","why":"Lysosomes digest worn-out organelles and cellular debris."},
        {"q":"Rough ER is 'rough' because it's studded with…","choices":["Ribosomes","Lysosomes","Vacuoles","Cilia"],"sub":"Site of protein synthesis","why":"Ribosomes on the rough ER make proteins for export."},
        {"q":"Which structure gives <b>plant</b> cells their rigid shape?","choices":["Cell wall","Cell membrane","Cytoskeleton","Vacuole"],"sub":"Outside the membrane, made of cellulose","why":"The cellulose cell wall provides structural support in plants."},
        {"q":"A large central <b>vacuole</b> in a plant cell mostly…","choices":["Stores water and maintains turgor","Makes proteins","Copies DNA","Produces ATP"],"sub":"Keeps the plant firm","why":"The central vacuole stores water, giving turgor pressure."},
      ],
      [
        {"q":"Which pair are both <b>double-membrane</b> organelles?","choices":["Mitochondrion & chloroplast","Ribosome & lysosome","Golgi & vacuole","Nucleolus & cytoplasm"],"sub":"Endosymbiotic theory hint","why":"Both mitochondria and chloroplasts have double membranes and their own DNA."},
        {"q":"Smooth ER is best known for…","choices":["Synthesizing lipids","Making proteins","Storing genetic code","Photosynthesis"],"sub":"No ribosomes attached","why":"Smooth ER synthesizes lipids and detoxifies chemicals."},
        {"q":"Which is found in an <b>animal</b> cell but NOT a typical plant cell?","choices":["Centrioles","Cell wall","Chloroplast","Large central vacuole"],"sub":"Helps organize cell division","why":"Centrioles organize spindle fibers during animal cell division."},
        {"q":"The <b>nucleolus</b> (inside the nucleus) makes…","choices":["Ribosomes","Lysosomes","ATP","Chlorophyll"],"sub":"Ribosome assembly line","why":"The nucleolus assembles ribosomal subunits."},
        {"q":"Prokaryotes differ from eukaryotes because they LACK…","choices":["A membrane-bound nucleus","Ribosomes","DNA","A cell membrane"],"sub":"Bacteria are prokaryotes","why":"Prokaryotes have no nucleus; their DNA floats in the cytoplasm."},
      ],
    ],
  },
  {
    "id": "photosynthesis-respiration-blitz", "title": "Photo-Respiration Blitz", "emoji": "🌿",
    "grades": "Gr 7-12", "topic": "Biology", "subject": "Science",
    "desc": "Master the two reactions that power life — inputs, outputs, and where they happen",
    "skills": ["photosynthesis", "cellular respiration", "ATP", "energy flow"],
    "difficulty": "hard", "time": 12, "caPoints": ["NGSS.HS-LS1-5", "NGSS.HS-LS1-7"],
    "palette": "bio",
    "levels": [
      [
        {"q":"Photosynthesis takes in CO₂ and water and produces…","choices":["Glucose and oxygen","Only oxygen","ATP and CO₂","Nitrogen and water"],"sub":"Light energy → chemical energy","why":"6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂."},
        {"q":"Cellular respiration releases energy by breaking down…","choices":["Glucose","Oxygen","Water","Carbon dioxide"],"sub":"The reverse of photosynthesis, roughly","why":"Glucose is oxidized to release energy stored as ATP."},
        {"q":"What gas do humans breathe OUT that plants use?","choices":["Carbon dioxide","Oxygen","Nitrogen","Hydrogen"],"sub":"A key photosynthesis input","why":"We exhale CO₂, which plants use in photosynthesis."},
        {"q":"Which pigment captures light in plants?","choices":["Chlorophyll","Hemoglobin","Keratin","Melanin"],"sub":"Makes leaves green","why":"Chlorophyll absorbs red and blue light for photosynthesis."},
        {"q":"The energy 'currency' molecule of the cell is…","choices":["ATP","DNA","NaCl","H₂O"],"sub":"Adenosine triphosphate","why":"ATP stores and delivers energy for cellular work."},
      ],
      [
        {"q":"Photosynthesis happens in the… ","choices":["Chloroplast","Mitochondrion","Nucleus","Ribosome"],"sub":"Green organelle","why":"Chloroplasts are the site of photosynthesis."},
        {"q":"Aerobic respiration happens mainly in the…","choices":["Mitochondrion","Chloroplast","Cytoplasm only","Vacuole"],"sub":"Powerhouse of the cell","why":"The mitochondrion runs the Krebs cycle and electron transport chain."},
        {"q":"The overall INPUTS of cellular respiration are…","choices":["Glucose + oxygen","CO₂ + water","ATP + light","Nitrogen + glucose"],"sub":"Aerobic version","why":"Respiration uses glucose and O₂, producing CO₂, water, and ATP."},
        {"q":"The light-dependent reactions of photosynthesis produce…","choices":["ATP and NADPH","Glucose directly","Only CO₂","Only water"],"sub":"They power the Calvin cycle","why":"Light reactions make ATP and NADPH used to fix carbon."},
        {"q":"In which does the Calvin cycle occur?","choices":["Stroma of the chloroplast","Thylakoid membrane","Mitochondrial matrix","Cell wall"],"sub":"The 'dark' reactions","why":"The Calvin cycle fixes CO₂ into sugar in the stroma."},
      ],
      [
        {"q":"Net ATP yield from aerobic respiration of one glucose is about…","choices":["30–38 ATP","2 ATP","100 ATP","0 ATP"],"sub":"Glycolysis + Krebs + ETC","why":"Complete aerobic respiration yields roughly 30–38 ATP per glucose."},
        {"q":"Glycolysis occurs in the…","choices":["Cytoplasm","Mitochondrial matrix","Nucleus","Chloroplast"],"sub":"First stage, no oxygen needed","why":"Glycolysis splits glucose into pyruvate in the cytoplasm."},
        {"q":"Fermentation happens when… ","choices":["Oxygen is absent","Oxygen is abundant","Light is present","DNA replicates"],"sub":"Anaerobic backup pathway","why":"Without O₂, cells ferment to regenerate NAD⁺ for glycolysis."},
        {"q":"Photosynthesis and respiration together form a cycle of…","choices":["Carbon and oxygen","Nitrogen and sulfur","Sodium and chlorine","Iron and copper"],"sub":"Each other's inputs and outputs","why":"The gases and carbon cycle between the two processes."},
        {"q":"The final electron acceptor in aerobic respiration is…","choices":["Oxygen","Carbon dioxide","Water","Glucose"],"sub":"Forms water at the end","why":"O₂ accepts electrons at the end of the electron transport chain, forming water."},
      ],
    ],
  },
  {
    "id": "genetics-punnett-quest", "title": "Genetics & Punnett Quest", "emoji": "🧬",
    "grades": "Gr 7-12", "topic": "Biology", "subject": "Science",
    "desc": "Predict inheritance with Punnett squares — dominant, recessive, ratios, and probability",
    "skills": ["genetics", "punnett squares", "heredity", "probability", "alleles"],
    "difficulty": "hard", "time": 13, "caPoints": ["NGSS.HS-LS3-3", "NGSS.MS-LS3-2"],
    "palette": "bio",
    "levels": [
      [
        {"q":"An allele written as a <b>capital</b> letter (e.g. T) is usually…","choices":["Dominant","Recessive","Codominant","Sex-linked"],"sub":"It masks the other allele","why":"By convention, capital letters denote dominant alleles."},
        {"q":"An organism's genetic makeup (e.g. Tt) is its…","choices":["Genotype","Phenotype","Karyotype","Ecotype"],"sub":"The actual alleles","why":"Genotype = the alleles; phenotype = the visible trait."},
        {"q":"'Tt' is described as…","choices":["Heterozygous","Homozygous dominant","Homozygous recessive","Haploid"],"sub":"Two different alleles","why":"Two different alleles (Tt) is heterozygous."},
        {"q":"A recessive trait only appears when the genotype is…","choices":["Homozygous recessive (tt)","Heterozygous (Tt)","Homozygous dominant (TT)","Any of these"],"sub":"Both alleles recessive","why":"Recessive traits show only with two recessive alleles."},
        {"q":"Cross TT × tt. What fraction of offspring are Tt?","choices":["All (100%)","Half (50%)","One quarter (25%)","None (0%)"],"sub":"Every box gets one T and one t","why":"TT × tt gives all Tt offspring."},
      ],
      [
        {"q":"Cross Tt × Tt. Ratio of dominant to recessive <b>phenotype</b>?","choices":["3 : 1","1 : 1","1 : 2 : 1","4 : 0"],"sub":"Classic monohybrid cross","why":"Tt × Tt gives 3 dominant : 1 recessive phenotype."},
        {"q":"Cross Tt × Tt. What is the <b>genotype</b> ratio?","choices":["1 TT : 2 Tt : 1 tt","3 : 1","1 : 1","All Tt"],"sub":"Count the four boxes","why":"The genotype ratio is 1:2:1 (TT:Tt:tt)."},
        {"q":"Cross Tt × tt. Chance of a recessive (tt) offspring?","choices":["50%","25%","75%","0%"],"sub":"Half the boxes are tt","why":"Tt × tt yields 50% Tt and 50% tt."},
        {"q":"In codominance (e.g. blood type AB), the heterozygote…","choices":["Shows both traits fully","Shows a blend","Shows only dominant","Shows only recessive"],"sub":"Both alleles expressed","why":"Codominance expresses both alleles at once, like type AB blood."},
        {"q":"A trait carried on the X chromosome is called…","choices":["Sex-linked","Autosomal","Polygenic","Codominant"],"sub":"More common in males","why":"X-linked (sex-linked) traits are carried on the X chromosome."},
      ],
      [
        {"q":"Two carriers (Aa × Aa) — probability a child is a carrier (Aa)?","choices":["1/2","1/4","3/4","1"],"sub":"The Tt boxes","why":"Aa × Aa gives 1/4 AA, 1/2 Aa, 1/4 aa — half are carriers."},
        {"q":"Incomplete dominance (red × white → pink) shows…","choices":["A blended phenotype","Both traits fully","Only red","A 3:1 ratio"],"sub":"Heterozygote is intermediate","why":"Incomplete dominance blends the two phenotypes."},
        {"q":"A dihybrid cross (RrYy × RrYy) gives a phenotype ratio of…","choices":["9 : 3 : 3 : 1","3 : 1","1 : 1 : 1 : 1","1 : 2 : 1"],"sub":"Two traits at once","why":"The classic dihybrid ratio is 9:3:3:1."},
        {"q":"If a colorblind father (XᶜY) has kids with a non-carrier mother (XX), the sons are…","choices":["All unaffected","All colorblind","Half colorblind","All carriers"],"sub":"Sons get Y from dad, X from mom","why":"Sons inherit the mother's normal X, so none are colorblind."},
        {"q":"The probability of two independent events BOTH happening is found by…","choices":["Multiplying their probabilities","Adding them","Subtracting them","Averaging them"],"sub":"The product rule","why":"Independent probabilities multiply (e.g. 1/2 × 1/2 = 1/4)."},
      ],
    ],
  },
  # ───────────────────────── HIGH SCHOOL CHEMISTRY ─────────────────────────
  {
    "id": "chem-bonding-blitz", "title": "Chemical Bonding Blitz", "emoji": "⚛️",
    "grades": "Gr 8-12", "topic": "Chemistry", "subject": "Science",
    "desc": "Ionic vs covalent, electrons, and polarity — the bonding questions that dominate chem exams",
    "skills": ["chemical bonds", "ionic", "covalent", "electronegativity", "valence electrons"],
    "difficulty": "hard", "time": 12, "caPoints": ["NGSS.HS-PS1-1", "NGSS.HS-PS1-2"],
    "palette": "chem",
    "levels": [
      [
        {"q":"An <b>ionic bond</b> forms when electrons are…","choices":["Transferred","Shared equally","Shared unequally","Destroyed"],"sub":"Metal + nonmetal","why":"Ionic bonds transfer electrons, forming charged ions."},
        {"q":"A <b>covalent bond</b> forms when electrons are…","choices":["Shared","Transferred","Removed","Added to the nucleus"],"sub":"Nonmetal + nonmetal","why":"Covalent bonds share electron pairs between atoms."},
        {"q":"Electrons involved in bonding are the… ","choices":["Valence electrons","Core electrons","Neutrons","Protons"],"sub":"Outermost shell","why":"Valence (outer-shell) electrons form chemical bonds."},
        {"q":"Table salt (NaCl) is held together by a(n)…","choices":["Ionic bond","Covalent bond","Metallic bond","Hydrogen bond"],"sub":"Sodium gives, chlorine takes","why":"Na⁺ and Cl⁻ attract in an ionic bond."},
        {"q":"Atoms bond to achieve a full… ","choices":["Outer electron shell","Nucleus","Set of neutrons","Charge of +2"],"sub":"The octet rule","why":"Atoms bond to reach a stable full outer shell (octet)."},
      ],
      [
        {"q":"Which pair will most likely form an ionic bond?","choices":["Na and Cl","O and O","C and H","N and N"],"sub":"Metal + nonmetal","why":"A metal (Na) and nonmetal (Cl) form an ionic bond."},
        {"q":"A molecule with unequal electron sharing is…","choices":["Polar","Nonpolar","Ionic","Metallic"],"sub":"One end slightly negative","why":"Unequal sharing creates a polar covalent bond."},
        {"q":"How many electrons does a single covalent bond share?","choices":["2","1","4","8"],"sub":"One pair","why":"A single bond shares one pair (2 electrons)."},
        {"q":"Electronegativity measures an atom's tendency to…","choices":["Attract shared electrons","Lose protons","Gain neutrons","Emit light"],"sub":"Higher = pulls electrons harder","why":"Electronegativity is the pull an atom has on bonding electrons."},
        {"q":"Metallic bonding is described as a 'sea of…'","choices":["Delocalized electrons","Protons","Neutrons","Ions only"],"sub":"Why metals conduct","why":"Metals share a sea of mobile, delocalized electrons."},
      ],
      [
        {"q":"Water (H₂O) is a polar molecule because…","choices":["Oxygen pulls electrons and it's bent","It is perfectly symmetrical","It has ionic bonds","It has no lone pairs"],"sub":"Shape + electronegativity","why":"O is electronegative and the bent shape makes H₂O polar."},
        {"q":"A double bond shares how many electrons?","choices":["4","2","6","1"],"sub":"Two pairs","why":"A double bond shares two pairs (4 electrons)."},
        {"q":"CO₂ has polar bonds but is nonpolar overall because…","choices":["It is linear and symmetric","Oxygen isn't electronegative","It's ionic","It has lone pairs on carbon"],"sub":"Dipoles cancel","why":"CO₂'s linear symmetry cancels the bond dipoles."},
        {"q":"Which bond type generally has the highest melting point?","choices":["Ionic","Nonpolar covalent","Hydrogen bond","London dispersion"],"sub":"Strong lattice forces","why":"Ionic compounds form strong lattices with high melting points."},
        {"q":"A hydrogen bond is a strong attraction between H and…","choices":["N, O, or F","C or S","Na or K","He or Ne"],"sub":"Explains water's properties","why":"Hydrogen bonds occur between H and N, O, or F."},
      ],
    ],
  },
  {
    "id": "balancing-equations-arena", "title": "Balancing Equations Arena", "emoji": "🧪",
    "grades": "Gr 8-12", "topic": "Chemistry", "subject": "Science",
    "desc": "Conserve mass by balancing reactions — the skill every chemistry exam demands",
    "skills": ["balancing equations", "conservation of mass", "stoichiometry", "coefficients"],
    "difficulty": "hard", "time": 13, "caPoints": ["NGSS.HS-PS1-7", "NGSS.MS-PS1-5"],
    "palette": "chem",
    "levels": [
      [
        {"q":"Balancing keeps which quantity equal on both sides?","choices":["Number of atoms of each element","Number of molecules","Temperature","Volume"],"sub":"Law of conservation of mass","why":"Atoms of each element must be equal on both sides."},
        {"q":"Balance: H₂ + O₂ → H₂O. Coefficient on H₂O?","choices":["2","1","3","4"],"sub":"2H₂ + O₂ → ?","why":"2H₂ + O₂ → 2H₂O balances all atoms."},
        {"q":"You balance an equation by changing…","choices":["Coefficients","Subscripts","Element symbols","The arrow"],"sub":"Never change subscripts","why":"Only coefficients may change; subscripts define the compound."},
        {"q":"In 2H₂O, how many hydrogen atoms are there?","choices":["4","2","1","6"],"sub":"Coefficient × subscript","why":"2 × 2 = 4 hydrogen atoms."},
        {"q":"Balance: N₂ + H₂ → NH₃. Coefficient on H₂?","choices":["3","1","2","4"],"sub":"N₂ + 3H₂ → 2NH₃","why":"N₂ + 3H₂ → 2NH₃ balances N and H."},
      ],
      [
        {"q":"Balance: CH₄ + O₂ → CO₂ + H₂O. Coefficient on O₂?","choices":["2","1","3","4"],"sub":"Combustion of methane","why":"CH₄ + 2O₂ → CO₂ + 2H₂O."},
        {"q":"Balance: Fe + O₂ → Fe₂O₃. Coefficient on Fe?","choices":["4","2","1","3"],"sub":"4Fe + 3O₂ → 2Fe₂O₃","why":"4Fe + 3O₂ → 2Fe₂O₃ balances iron and oxygen."},
        {"q":"A reaction A + B → AB is a…","choices":["Synthesis reaction","Decomposition","Single replacement","Combustion"],"sub":"Two combine into one","why":"Two reactants forming one product is synthesis."},
        {"q":"AB → A + B is a…","choices":["Decomposition reaction","Synthesis","Combustion","Neutralization"],"sub":"One breaks into parts","why":"One compound breaking apart is decomposition."},
        {"q":"Balance: Al + Cl₂ → AlCl₃. Coefficient on Cl₂?","choices":["3","2","1","4"],"sub":"2Al + 3Cl₂ → 2AlCl₃","why":"2Al + 3Cl₂ → 2AlCl₃."},
      ],
      [
        {"q":"Balance: C₃H₈ + O₂ → CO₂ + H₂O. Coefficient on O₂?","choices":["5","3","4","6"],"sub":"Propane combustion","why":"C₃H₈ + 5O₂ → 3CO₂ + 4H₂O."},
        {"q":"A + BC → AC + B describes a…","choices":["Single-replacement reaction","Double replacement","Synthesis","Decomposition"],"sub":"One element swaps in","why":"One element replacing another is single replacement."},
        {"q":"Balance: KClO₃ → KCl + O₂. Coefficient on KClO₃?","choices":["2","1","3","4"],"sub":"2KClO₃ → 2KCl + 3O₂","why":"2KClO₃ → 2KCl + 3O₂ balances the equation."},
        {"q":"In a balanced equation, total mass of reactants vs products?","choices":["Exactly equal","Reactants greater","Products greater","Depends on temperature"],"sub":"Nothing is lost","why":"Mass is conserved — reactant mass equals product mass."},
        {"q":"Balance: Ca(OH)₂ + HCl → CaCl₂ + H₂O. Coefficient on HCl?","choices":["2","1","3","4"],"sub":"Acid-base neutralization","why":"Ca(OH)₂ + 2HCl → CaCl₂ + 2H₂O."},
      ],
    ],
  },
  {
    "id": "ph-acids-bases-rush", "title": "pH, Acids & Bases Rush", "emoji": "🧫",
    "grades": "Gr 6-12", "topic": "Chemistry", "subject": "Science",
    "desc": "Read the pH scale and tell acids from bases — a guaranteed exam topic",
    "skills": ["acids and bases", "pH scale", "indicators", "neutralization"],
    "difficulty": "medium", "time": 11, "caPoints": ["NGSS.MS-PS1-2", "NGSS.HS-PS1-6"],
    "palette": "chem",
    "levels": [
      [
        {"q":"On the pH scale, 7 means the solution is…","choices":["Neutral","Strongly acidic","Strongly basic","Radioactive"],"sub":"Like pure water","why":"pH 7 is neutral — equal H⁺ and OH⁻."},
        {"q":"A pH of 2 is…","choices":["Acidic","Basic","Neutral","Impossible"],"sub":"Below 7","why":"pH below 7 is acidic; 2 is strongly acidic."},
        {"q":"A pH of 12 is…","choices":["Basic","Acidic","Neutral","Salty only"],"sub":"Above 7","why":"pH above 7 is basic (alkaline)."},
        {"q":"Which is an everyday <b>acid</b>?","choices":["Lemon juice","Soap","Baking soda","Bleach"],"sub":"Sour taste","why":"Lemon juice (citric acid) is acidic."},
        {"q":"Litmus paper turns <b>red</b> in…","choices":["Acids","Bases","Neutral water","Oil"],"sub":"Classic indicator","why":"Acids turn blue litmus red."},
      ],
      [
        {"q":"Acids release which ion in water?","choices":["H⁺ (hydrogen)","OH⁻ (hydroxide)","Na⁺","Cl⁻"],"sub":"Proton donors","why":"Acids donate H⁺ ions in solution."},
        {"q":"Bases release which ion in water?","choices":["OH⁻ (hydroxide)","H⁺","Cl⁻","CO₂"],"sub":"Hydroxide ions","why":"Bases release OH⁻ ions in solution."},
        {"q":"Acid + base react to form water and a…","choices":["Salt","Gas only","Metal","New acid"],"sub":"Neutralization","why":"Neutralization produces water and a salt."},
        {"q":"The pH scale typically ranges from…","choices":["0 to 14","1 to 100","0 to 7","−7 to 7"],"sub":"Standard range","why":"pH usually runs from 0 (acidic) to 14 (basic)."},
        {"q":"Each pH unit represents a factor of ___ in acidity.","choices":["10","2","5","100"],"sub":"Logarithmic scale","why":"pH is logarithmic — each unit is a 10× change in H⁺."},
      ],
      [
        {"q":"A solution changes from pH 5 to pH 3. It became…","choices":["100× more acidic","2× more acidic","Less acidic","Neutral"],"sub":"Two units on a log scale","why":"Two pH units = 10², so 100× more acidic."},
        {"q":"A strong acid is one that…","choices":["Fully ionizes in water","Barely ionizes","Has a high pH","Contains no H⁺"],"sub":"Complete dissociation","why":"Strong acids dissociate completely into ions."},
        {"q":"Which is a common strong base?","choices":["Sodium hydroxide (NaOH)","Vinegar","Carbonic acid","Sugar water"],"sub":"Lye","why":"NaOH is a strong base that fully dissociates."},
        {"q":"A buffer solution is designed to…","choices":["Resist changes in pH","Always stay acidic","Increase pH forever","Conduct no electricity"],"sub":"Keeps pH stable","why":"Buffers resist pH change when acid or base is added."},
        {"q":"At pH 7, the concentration of H⁺ vs OH⁻ is…","choices":["Equal","H⁺ greater","OH⁻ greater","Zero for both"],"sub":"Definition of neutral","why":"Neutral means [H⁺] = [OH⁻]."},
      ],
    ],
  },
  # ───────────────────────── HIGH SCHOOL PHYSICS ─────────────────────────
  {
    "id": "newtons-laws-arena", "title": "Newton's Laws Arena", "emoji": "🍎",
    "grades": "Gr 6-12", "topic": "Physics", "subject": "Science",
    "desc": "Force, mass, and motion — the three laws exams test again and again",
    "skills": ["newton's laws", "force", "inertia", "acceleration", "F=ma"],
    "difficulty": "medium", "time": 12, "caPoints": ["NGSS.HS-PS2-1", "NGSS.MS-PS2-2"],
    "palette": "phys",
    "levels": [
      [
        {"q":"Newton's 1st law says an object at rest tends to…","choices":["Stay at rest","Speed up","Fall down","Disappear"],"sub":"Law of inertia","why":"Objects keep their state of motion unless a force acts."},
        {"q":"The tendency of objects to resist changes in motion is…","choices":["Inertia","Gravity","Friction","Momentum"],"sub":"Related to mass","why":"Inertia is resistance to changes in motion."},
        {"q":"Newton's 2nd law is written as…","choices":["F = ma","E = mc²","v = d/t","P = IV"],"sub":"Force, mass, acceleration","why":"Force equals mass times acceleration (F = ma)."},
        {"q":"For every action there is an equal and opposite…","choices":["Reaction","Acceleration","Mass","Distance"],"sub":"Newton's 3rd law","why":"Newton's 3rd law: forces come in equal, opposite pairs."},
        {"q":"A force is a…","choices":["Push or pull","Type of energy","Unit of mass","Speed"],"sub":"Measured in newtons","why":"A force is a push or pull, measured in newtons (N)."},
      ],
      [
        {"q":"F = ma. If m = 2 kg and a = 3 m/s², then F =","choices":["6 N","5 N","1.5 N","8 N"],"sub":"Multiply mass by acceleration","why":"F = 2 × 3 = 6 N."},
        {"q":"Same force on a heavier object gives ___ acceleration.","choices":["Less","More","The same","Zero"],"sub":"a = F/m","why":"Larger mass means smaller acceleration for the same force."},
        {"q":"A rocket pushes gas down and moves up. This is Newton's…","choices":["3rd law","1st law","2nd law","Law of gravity"],"sub":"Action–reaction","why":"Thrust is the reaction to expelling gas — Newton's 3rd law."},
        {"q":"A seatbelt protects you in a crash because of…","choices":["Inertia","Gravity","Magnetism","Buoyancy"],"sub":"Your body wants to keep moving","why":"Inertia keeps you moving forward; the belt applies the stopping force."},
        {"q":"Net force of zero means the object has…","choices":["No acceleration","Increasing speed","Zero mass","Infinite velocity"],"sub":"Balanced forces","why":"Zero net force means no acceleration (constant velocity)."},
      ],
      [
        {"q":"F = ma. A 1500 kg car accelerates at 2 m/s². Net force?","choices":["3000 N","750 N","1502 N","3 N"],"sub":"m × a","why":"1500 × 2 = 3000 N."},
        {"q":"Weight is the force of gravity, so weight equals…","choices":["mass × g","mass ÷ g","mass + g","mass only"],"sub":"g ≈ 9.8 m/s²","why":"Weight W = mg, where g is gravitational acceleration."},
        {"q":"On the Moon your MASS compared to Earth is…","choices":["The same","Less","More","Zero"],"sub":"Mass ≠ weight","why":"Mass is constant; only weight changes with gravity."},
        {"q":"A 10 N force accelerates a mass at 5 m/s². The mass is…","choices":["2 kg","50 kg","0.5 kg","15 kg"],"sub":"m = F/a","why":"m = 10 / 5 = 2 kg."},
        {"q":"Friction always acts…","choices":["Opposite to motion","In the direction of motion","Upward","Toward the center"],"sub":"It resists sliding","why":"Friction opposes the relative motion between surfaces."},
      ],
    ],
  },
  {
    "id": "energy-forms-blitz", "title": "Energy Forms Blitz", "emoji": "⚡",
    "grades": "Gr 5-12", "topic": "Physics", "subject": "Science",
    "desc": "Kinetic, potential, and conservation of energy — high-yield exam concepts",
    "skills": ["energy", "kinetic energy", "potential energy", "conservation of energy", "transformations"],
    "difficulty": "medium", "time": 11, "caPoints": ["NGSS.HS-PS3-1", "NGSS.MS-PS3-5"],
    "palette": "phys",
    "levels": [
      [
        {"q":"Energy of <b>motion</b> is called…","choices":["Kinetic energy","Potential energy","Chemical energy","Nuclear energy"],"sub":"A moving car has it","why":"Kinetic energy is the energy of motion."},
        {"q":"Stored energy due to <b>position</b> is…","choices":["Potential energy","Kinetic energy","Thermal energy","Sound energy"],"sub":"A ball at the top of a hill","why":"Potential energy is stored due to position or height."},
        {"q":"Energy from the Sun is mostly…","choices":["Light (radiant) energy","Sound energy","Nuclear energy on Earth","Electrical energy"],"sub":"Travels as waves","why":"The Sun delivers radiant (light) energy."},
        {"q":"Energy stored in food and batteries is…","choices":["Chemical energy","Kinetic energy","Sound energy","Elastic energy"],"sub":"Released by reactions","why":"Chemical energy is stored in bonds, released in reactions."},
        {"q":"When you stretch a rubber band you store…","choices":["Elastic potential energy","Thermal energy","Nuclear energy","Sound energy"],"sub":"Springs and bands","why":"Stretched or compressed objects store elastic potential energy."},
      ],
      [
        {"q":"A falling ball converts potential energy into…","choices":["Kinetic energy","Chemical energy","Nuclear energy","Sound energy only"],"sub":"As it speeds up","why":"Height (PE) converts to speed (KE) as it falls."},
        {"q":"The law of conservation of energy says energy is…","choices":["Never created or destroyed","Always increasing","Always lost","Only stored"],"sub":"Only transformed","why":"Energy is conserved — it only changes form."},
        {"q":"A toaster mainly converts electrical energy into…","choices":["Thermal (heat) energy","Chemical energy","Nuclear energy","Sound energy"],"sub":"Glowing coils","why":"A toaster turns electrical energy into heat."},
        {"q":"Where does a pendulum have the most kinetic energy?","choices":["At the bottom of the swing","At the highest point","At the endpoints","Nowhere"],"sub":"Fastest point","why":"KE is greatest at the bottom where speed is highest."},
        {"q":"Gravitational PE increases when an object is…","choices":["Raised higher","Made colder","Slowed down","Painted"],"sub":"PE = mgh","why":"PE = mgh, so raising height raises potential energy."},
      ],
      [
        {"q":"KE = ½mv². If speed doubles, kinetic energy…","choices":["Quadruples (×4)","Doubles (×2)","Halves","Stays the same"],"sub":"v is squared","why":"KE ∝ v², so doubling v gives 4× the energy."},
        {"q":"A roller coaster is slowest at the…","choices":["Highest point","Lowest point","Middle","Start only"],"sub":"Most PE, least KE","why":"At the top, energy is mostly potential, so speed is lowest."},
        {"q":"'Lost' energy in real machines usually becomes…","choices":["Heat from friction","New matter","Extra fuel","Light only"],"sub":"Why nothing is 100% efficient","why":"Friction turns useful energy into waste heat."},
        {"q":"A 2 kg ball is 5 m high (g≈10). Its PE is about…","choices":["100 J","10 J","25 J","7 J"],"sub":"PE = mgh","why":"PE = 2 × 10 × 5 = 100 J."},
        {"q":"Efficiency of a machine is useful output energy divided by…","choices":["Total input energy","Its mass","Its speed","The time taken"],"sub":"Always ≤ 100%","why":"Efficiency = useful output ÷ total input energy."},
      ],
    ],
  },
  {
    "id": "waves-light-quest", "title": "Waves & Light Quest", "emoji": "🌊",
    "grades": "Gr 6-12", "topic": "Physics", "subject": "Science",
    "desc": "Wavelength, frequency, and the electromagnetic spectrum — core physics exam material",
    "skills": ["waves", "light", "electromagnetic spectrum", "frequency", "wavelength"],
    "difficulty": "medium", "time": 12, "caPoints": ["NGSS.HS-PS4-1", "NGSS.MS-PS4-2"],
    "palette": "phys",
    "levels": [
      [
        {"q":"The distance between two wave crests is the…","choices":["Wavelength","Amplitude","Frequency","Period"],"sub":"Crest to crest","why":"Wavelength is the distance between successive crests."},
        {"q":"The height of a wave from rest is its…","choices":["Amplitude","Wavelength","Frequency","Speed"],"sub":"Relates to energy/loudness","why":"Amplitude measures a wave's height and its energy."},
        {"q":"Number of waves passing per second is the…","choices":["Frequency","Wavelength","Amplitude","Medium"],"sub":"Measured in hertz","why":"Frequency is waves per second, measured in Hz."},
        {"q":"Sound waves need a ___ to travel.","choices":["Medium (matter)","Vacuum","Magnet","Battery"],"sub":"They can't cross empty space","why":"Sound needs matter; it can't travel through a vacuum."},
        {"q":"Light is a type of ___ wave.","choices":["Electromagnetic","Sound","Water","Seismic"],"sub":"Travels through space","why":"Light is an electromagnetic wave and needs no medium."},
      ],
      [
        {"q":"Higher frequency means ___ wavelength.","choices":["Shorter","Longer","No change in","Doubled"],"sub":"They're inversely related","why":"Frequency and wavelength are inversely proportional."},
        {"q":"Which has the longest wavelength?","choices":["Radio waves","Visible light","X-rays","Gamma rays"],"sub":"Low-energy end","why":"Radio waves have the longest wavelength, lowest energy."},
        {"q":"Which travels fastest in a vacuum?","choices":["Light","Sound","Water waves","Nothing moves"],"sub":"About 3×10⁸ m/s","why":"Light in a vacuum travels at ~300,000 km/s."},
        {"q":"When a wave bounces off a surface it is…","choices":["Reflected","Refracted","Absorbed","Diffracted"],"sub":"Like an echo or mirror","why":"Bouncing off a surface is reflection."},
        {"q":"A wave bending as it enters water is…","choices":["Refraction","Reflection","Absorption","Amplification"],"sub":"Speed change bends it","why":"Refraction is the bending of a wave as its speed changes."},
      ],
      [
        {"q":"Wave speed = frequency × wavelength. f=2 Hz, λ=3 m → v =","choices":["6 m/s","1.5 m/s","5 m/s","0.67 m/s"],"sub":"Multiply them","why":"v = f × λ = 2 × 3 = 6 m/s."},
        {"q":"Which EM waves have the HIGHEST energy?","choices":["Gamma rays","Radio waves","Microwaves","Infrared"],"sub":"Shortest wavelength","why":"Gamma rays have the shortest wavelength and highest energy."},
        {"q":"A pitch we hear as 'higher' corresponds to ___ frequency.","choices":["Higher","Lower","Zero","Negative"],"sub":"Pitch ~ frequency","why":"Higher-frequency sound is heard as higher pitch."},
        {"q":"In a transverse wave, particles move…","choices":["Perpendicular to wave travel","Along the wave direction","In circles only","Not at all"],"sub":"Like a rope wave","why":"Transverse wave particles move perpendicular to travel direction."},
        {"q":"The Doppler effect explains why a passing siren's pitch…","choices":["Drops as it moves away","Stays exactly constant","Only gets louder","Becomes silent"],"sub":"Waves compress then stretch","why":"Approaching waves compress (higher pitch); receding stretch (lower)."},
      ],
    ],
  },
  # ───────────────────────── EARTH & SPACE (exam staples) ─────────────────────────
  {
    "id": "earth-systems-rush", "title": "Earth Systems Rush", "emoji": "🌍",
    "grades": "Gr 4-10", "topic": "Earth Science", "subject": "Science",
    "desc": "Rock cycle, plate tectonics, and Earth's layers — earth-science test essentials",
    "skills": ["rock cycle", "plate tectonics", "earth's layers", "weathering", "geology"],
    "difficulty": "medium", "time": 12, "caPoints": ["NGSS.MS-ESS2-1", "NGSS.HS-ESS2-1"],
    "palette": "earth",
    "levels": [
      [
        {"q":"Earth's outermost solid layer is the…","choices":["Crust","Mantle","Outer core","Inner core"],"sub":"Where we live","why":"The crust is Earth's thin, solid outer layer."},
        {"q":"The very center of Earth, the inner core, is mostly…","choices":["Solid iron and nickel","Liquid water","Molten rock","Gas"],"sub":"Extremely hot but solid","why":"Immense pressure keeps the iron-nickel inner core solid."},
        {"q":"Rock formed from cooled lava or magma is…","choices":["Igneous","Sedimentary","Metamorphic","Fossil"],"sub":"'Fire' rock","why":"Igneous rock forms when magma or lava cools and solidifies."},
        {"q":"Layers of sediment pressed together form ___ rock.","choices":["Sedimentary","Igneous","Metamorphic","Liquid"],"sub":"Often holds fossils","why":"Sedimentary rock forms from compacted sediment layers."},
        {"q":"Breaking rock into smaller pieces by wind and water is…","choices":["Weathering","Melting","Eruption","Condensation"],"sub":"Physical breakdown","why":"Weathering breaks rock into smaller pieces over time."},
      ],
      [
        {"q":"Earth's crust is broken into moving pieces called…","choices":["Tectonic plates","Continents only","Craters","Fault lines"],"sub":"They float on the mantle","why":"Tectonic plates are large slabs of crust that move slowly."},
        {"q":"Most earthquakes happen at…","choices":["Plate boundaries","The equator","Mountain peaks","Ocean centers only"],"sub":"Where plates meet","why":"Earthquakes concentrate along tectonic plate boundaries."},
        {"q":"Rock changed by heat and pressure (not melting) is…","choices":["Metamorphic","Igneous","Sedimentary","Molten"],"sub":"'Changed form'","why":"Metamorphic rock forms under heat and pressure without melting."},
        {"q":"Molten rock BELOW the surface is called…","choices":["Magma","Lava","Sediment","Basalt"],"sub":"Above surface it's 'lava'","why":"Underground molten rock is magma; above ground it's lava."},
        {"q":"The moving of weathered material to a new place is…","choices":["Erosion","Deposition","Melting","Fossilization"],"sub":"Carried by wind, water, ice","why":"Erosion transports weathered material to new locations."},
      ],
      [
        {"q":"Two plates pushing together often form…","choices":["Mountains","Deep flat plains","No change","New oceans only"],"sub":"Convergent boundary","why":"Convergent boundaries can push crust up into mountains."},
        {"q":"The mantle moves via ___ currents that drive plate motion.","choices":["Convection","Radiation","Reflection","Electric"],"sub":"Hot rises, cool sinks","why":"Convection currents in the mantle drive plate tectonics."},
        {"q":"Plates sliding PAST each other form a ___ boundary.","choices":["Transform","Convergent","Divergent","Subduction"],"sub":"Like the San Andreas Fault","why":"Transform boundaries have plates sliding past one another."},
        {"q":"The rock cycle shows that any rock type can become…","choices":["Any other type","Only sedimentary","Only igneous","Never anything else"],"sub":"It's a continuous cycle","why":"With enough heat, pressure, or weathering, rocks convert between all three types."},
        {"q":"Sea-floor spreading occurs at a ___ boundary.","choices":["Divergent","Convergent","Transform","Continental only"],"sub":"Plates move apart","why":"Divergent boundaries pull apart, creating new sea floor."},
      ],
    ],
  },
  {
    "id": "solar-system-space-quest", "title": "Solar System & Space Quest", "emoji": "🪐",
    "grades": "Gr 3-10", "topic": "Space Science", "subject": "Science",
    "desc": "Planets, moons, gravity, and stars — the astronomy facts that show up on every test",
    "skills": ["solar system", "planets", "gravity", "stars", "moon phases", "astronomy"],
    "difficulty": "easy", "time": 11, "caPoints": ["NGSS.MS-ESS1-3", "NGSS.5-ESS1-2"],
    "palette": "space",
    "levels": [
      [
        {"q":"Which planet is closest to the Sun?","choices":["Mercury","Earth","Jupiter","Neptune"],"sub":"Smallest and fastest orbit","why":"Mercury is the innermost planet."},
        {"q":"Which is the largest planet in our solar system?","choices":["Jupiter","Earth","Saturn","Mars"],"sub":"A gas giant","why":"Jupiter is the biggest planet by far."},
        {"q":"The Sun is a…","choices":["Star","Planet","Moon","Comet"],"sub":"A giant ball of gas","why":"The Sun is the star at the center of our solar system."},
        {"q":"What keeps planets orbiting the Sun?","choices":["Gravity","Magnetism","Wind","Sound"],"sub":"An attractive force","why":"The Sun's gravity holds planets in orbit."},
        {"q":"Earth's natural satellite is the…","choices":["Moon","Sun","ISS","Mars"],"sub":"It orbits us","why":"The Moon is Earth's only natural satellite."},
      ],
      [
        {"q":"Which planet is famous for its rings?","choices":["Saturn","Mars","Venus","Mercury"],"sub":"Made of ice and rock","why":"Saturn's spectacular rings are made of ice and rock."},
        {"q":"The 'Red Planet' is…","choices":["Mars","Jupiter","Venus","Neptune"],"sub":"Rusty iron surface","why":"Iron oxide gives Mars its red color."},
        {"q":"A year is the time Earth takes to…","choices":["Orbit the Sun once","Spin once","Reach the Moon","Cross the galaxy"],"sub":"About 365 days","why":"One orbit around the Sun defines a year."},
        {"q":"A day is caused by Earth's…","choices":["Rotation on its axis","Orbit of the Sun","Distance from Mars","Tilt only"],"sub":"One spin ≈ 24 hours","why":"Earth's rotation causes day and night."},
        {"q":"Moon phases are caused by…","choices":["Its position relative to Earth and Sun","Earth's shadow always","Clouds","The Moon's own light"],"sub":"We see lit portions","why":"Phases depend on how much of the sunlit Moon faces us."},
      ],
      [
        {"q":"The force of gravity is stronger when objects are…","choices":["More massive and closer","Lighter and farther","Colder","Spinning faster"],"sub":"Newton's law of gravitation","why":"Gravity increases with mass and decreases with distance."},
        {"q":"Between the inner rocky planets and gas giants lies the…","choices":["Asteroid belt","Kuiper belt only","Oort cloud","Sun's core"],"sub":"Between Mars and Jupiter","why":"The asteroid belt sits between Mars and Jupiter."},
        {"q":"Stars produce energy through…","choices":["Nuclear fusion","Chemical burning","Friction","Electricity"],"sub":"Hydrogen into helium","why":"Stars fuse hydrogen into helium, releasing energy."},
        {"q":"A solar eclipse happens when the ___ passes between Sun and Earth.","choices":["Moon","Sun","Mars","Comet"],"sub":"Moon blocks the Sun","why":"In a solar eclipse the Moon blocks the Sun's light."},
        {"q":"Light from the Sun takes about 8 minutes to reach Earth because…","choices":["Light has a finite speed","The Sun is dim","Space slows it down","Gravity blocks it"],"sub":"~150 million km away","why":"Even at light speed, the distance takes ~8 minutes."},
      ],
    ],
  },
]
print("Defined", len(GAMES), "games,", sum(len(l) for g in GAMES for l in g["levels"]), "questions total")
