export const LABS = [
  {id:"projectile-motion",title:"Projectile Motion",emoji:"🚀",grades:"Gr 5-9",topic:"Physics",subject:"physics",desc:"Launch a projectile and hit the target — explore angle, speed, and gravity",skills:["projectile motion","trigonometry","kinematics","gravity"],difficulty:"medium",time:18,caPoints:["NGSS.MS-PS2-2"],prereq:["multiplication-blaster"],unlocks:["pendulum-lab","friction-incline"]},
  {id:"pendulum-lab",title:"Pendulum Lab",emoji:"🌀",grades:"Gr 6-10",topic:"Physics",subject:"physics",desc:"Vary length, mass, gravity — discover what controls the period",skills:["periodic motion","gravity","energy conservation"],difficulty:"medium",time:20,caPoints:["NGSS.MS-PS3-2","HS-PS2-2"],prereq:["projectile-motion"],unlocks:["wave-interference"]},
  {id:"friction-incline",title:"Friction & Inclined Plane",emoji:"📐",grades:"Gr 7-11",topic:"Physics",subject:"physics",desc:"Will it slide? Discover μ_static vs μ_kinetic on a ramp",skills:["friction","forces","Newton's laws","trigonometry"],difficulty:"medium",time:18,caPoints:["NGSS.MS-PS2-1","HS-PS2-1"],prereq:["projectile-motion"],unlocks:["wave-interference"]},
  {id:"wave-interference",title:"Wave Interference",emoji:"🌊",grades:"Gr 8-12",topic:"Physics",subject:"physics",desc:"Two ripple sources — discover constructive vs destructive interference",skills:["waves","interference","wavelength","superposition"],difficulty:"hard",time:22,caPoints:["NGSS.HS-PS4-1","HS-PS4-3"],prereq:["pendulum-lab"],unlocks:[]},
  {id:"spring-oscillator",title:"Spring Oscillator",emoji:"🪀",grades:"Gr 7-11",topic:"Physics",subject:"physics",desc:"Drag the mass, release, watch SHM — see Hooke's law in action",skills:["Hooke's law","SHM","energy conservation","oscillation"],difficulty:"medium",time:18,caPoints:["NGSS.MS-PS3-2","HS-PS2-2"],prereq:["pendulum-lab"],unlocks:["wave-interference"]},
  {id:"newtons-cradle",title:"Newton's Cradle",emoji:"🎱",grades:"Gr 6-10",topic:"Physics",subject:"physics",desc:"Lift 1 ball — 1 swings out. Lift 2 — 2 swing. Why?",skills:["momentum","kinetic energy","elastic collisions","conservation"],difficulty:"medium",time:15,caPoints:["NGSS.MS-PS2-3","HS-PS2-2","HS-PS2-3"],prereq:["projectile-motion"],unlocks:["spring-oscillator"]},
  {id:"electric-circuit",title:"Electric Circuit",emoji:"💡",grades:"Gr 6-10",topic:"Physics",subject:"physics",desc:"Build series & parallel circuits — Ohm's law made visible",skills:["Ohm's law","series","parallel","voltage","current","power"],difficulty:"medium",time:20,caPoints:["NGSS.MS-PS3-3","HS-PS3-3"],prereq:["multiplication-blaster"],unlocks:["wave-interference"]},
  {id:"multiplication-blaster",title:"Multiplication Blaster",emoji:"🎯",grades:"Gr 2-5",topic:"Multiplication",desc:"Build matrices by shooting paintballs to visualize multiplication",skills:["multiplication","arrays","visual math"],difficulty:"medium",time:15,caPoints:["CCSS.MATH.CONTENT.3.OA.A.1"]},
  {id:"division-cards",title:"Division Cards",emoji:"🃏",grades:"Gr 3-6",topic:"Division",desc:"Timed card game — 3 difficulty levels, 30-second rounds",skills:["division","fact fluency","mental math"],difficulty:"easy-hard",time:10,caPoints:["CCSS.MATH.CONTENT.3.OA.C.7"]},
  {id:"fractions-basic",title:"Fractions Basics",emoji:"🍕",grades:"Gr 3-5",topic:"Fractions",desc:"Visualize and understand what fractions represent",skills:["fractions","numerator","denominator"],difficulty:"easy",time:20,caPoints:["CCSS.MATH.CONTENT.3.NF.A.1"]},
  {id:"fractions-order",title:"Ordering Fractions",emoji:"📊",grades:"Gr 4-6",topic:"Fractions",desc:"Order fractions on a number line from smallest to largest",skills:["fractions","comparison","number line"],difficulty:"medium",time:20,caPoints:["CCSS.MATH.CONTENT.4.NF.A.2"]},
  {id:"negative-numbers",title:"Negative Numbers",emoji:"➖",grades:"Gr 5-7",topic:"Integers",desc:"Add and subtract negative numbers including fractions",skills:["integers","negative numbers","operations"],difficulty:"hard",time:25,caPoints:["CCSS.MATH.CONTENT.6.NS.C.5"]},
  {id:"commutative",title:"Commutative Property",emoji:"🔄",grades:"Gr 3-5",topic:"Properties",desc:"Discover that a×b = b×a through interactive experiments",skills:["properties","multiplication","algebra thinking"],difficulty:"easy",time:15,caPoints:["CCSS.MATH.CONTENT.3.OA.B.5"]},
  {id:"column-addition",title:"Column Addition",emoji:"🏗️",grades:"Gr 2-4",topic:"Addition",desc:"Master place values with step-by-step column addition",skills:["addition","place value","regrouping"],difficulty:"medium",time:20,caPoints:["CCSS.MATH.CONTENT.2.NBT.B.7"]},
  {id:"division-remainder",title:"Division with Remainder",emoji:"➗",grades:"Gr 3-5",topic:"Division",desc:"Explore even/odd and division with interactive grid",skills:["division","remainders","even/odd"],difficulty:"medium",time:20,caPoints:["CCSS.MATH.CONTENT.3.OA.C.7"]},
  {id:"multiply-by-1",title:"Multiply by 1",emoji:"1️⃣",grades:"Gr 2-3",topic:"Multiplication",desc:"Understand the identity property — any number × 1 = itself",skills:["identity property","multiplication","mental math"],difficulty:"easy",time:15,caPoints:["CCSS.MATH.CONTENT.3.OA.B.5"]},
  {id:"multiplication",title:"Multiplication Lab",emoji:"✖️",grades:"Gr 2-4",topic:"Multiplication",desc:"Full lab: theory, dot grid practice, and multiplication table",skills:["multiplication","arrays","fact fluency"],difficulty:"medium",time:25,caPoints:["CCSS.MATH.CONTENT.3.OA.A.1"]},
  {id:"rounding",title:"Rounding Numbers",emoji:"🎯",grades:"Gr 3-5",topic:"Number Sense",desc:"Interactive rounding with decimal precision control",skills:["rounding","estimation","place value"],difficulty:"medium",time:15,caPoints:["CCSS.MATH.CONTENT.3.NBT.A.1"]},
  {id:"multiplication-cards",title:"Multiplication Cards",emoji:"🎴",grades:"Gr 2-5",topic:"Multiplication",desc:"Flash card practice for multiplication fact mastery",skills:["fact fluency","multiplication","speed"],difficulty:"easy",time:10,caPoints:["CCSS.MATH.CONTENT.3.OA.C.7"]},
  {id:"bubbles",title:"Math Bubbles",emoji:"🫧",grades:"Gr 1-3",topic:"Arithmetic",desc:"Pop the bubble with the correct answer before time runs out",skills:["addition","subtraction","speed"],difficulty:"easy",time:10,caPoints:["CCSS.MATH.CONTENT.1.OA.C.6"]},
  {id:"even-odd-sum",title:"Even & Odd Sums",emoji:"⚖️",grades:"Gr 2-4",topic:"Number Properties",desc:"Learn and practice rules for sums of even and odd numbers",skills:["even/odd","addition","number properties"],difficulty:"easy",time:15,caPoints:["CCSS.MATH.CONTENT.2.OA.C.3"]},
  // ── Synthesis-inspired math labs (40 additional, from labs-pack) ──
  {id:"sx-adding-and-subtracting-decimals",title:"Adding and Subtracting Decimals",emoji:"🔢",grades:"Gr 4–7",topic:"Number Operations",desc:"Adding and Subtracting Decimals — interactive number operations lab",skills:["operations","integers","decimals"],difficulty:"medium",time:15,url:"./labs-pack/adding-and-subtracting-decimals/index.html",caPoints:[]},
  {id:"sx-adding-and-subtracting-negative-numbers",title:"Adding and Subtracting Negative Numbers",emoji:"🔢",grades:"Gr 4–7",topic:"Number Operations",desc:"Adding and Subtracting Negative Numbers — interactive number operations lab",skills:["operations","integers","decimals"],difficulty:"medium",time:15,url:"./labs-pack/adding-and-subtracting-negative-numbers/index.html",caPoints:[]},
  {id:"sx-bubbles-and-examples-fix-audio",title:"Bubbles and Examples Fix Audio",emoji:"🧮",grades:"Gr 2–6",topic:"Math Practice",desc:"Bubbles and Examples Fix Audio — interactive math practice lab",skills:["practice","fluency","speed"],difficulty:"medium",time:15,url:"./labs-pack/bubbles-and-examples-fix-audio/index.html",caPoints:[]},
  {id:"sx-changing-the-places-of-the-terms",title:"Changing the Places of the Terms",emoji:"🔄",grades:"Gr 2–5",topic:"Properties",desc:"Changing the Places of the Terms — interactive properties lab",skills:["commutative","associative","number properties"],difficulty:"easy",time:15,url:"./labs-pack/changing-the-places-of-the-terms/index.html",caPoints:[]},
  {id:"sx-column-addition-update",title:"Column Addition Update",emoji:"➕",grades:"Gr 1–4",topic:"Addition & Subtraction",desc:"Column Addition Update — interactive addition & subtraction lab",skills:["addition","subtraction","mental math"],difficulty:"easy",time:15,url:"./labs-pack/column-addition-update/index.html",caPoints:[]},
  {id:"sx-digits-of-numbers",title:"Digits of Numbers",emoji:"🎯",grades:"Gr 1–4",topic:"Number Sense",desc:"Digits of Numbers — interactive number sense lab",skills:["number sense","digit recognition"],difficulty:"easy",time:15,url:"./labs-pack/digits-of-numbers/Digits of numbers_RU/index.html",caPoints:[]},
  {id:"sx-division-cards-update",title:"Division Cards Update",emoji:"➗",grades:"Gr 3–5",topic:"Division",desc:"Division Cards Update — interactive division lab",skills:["division","remainders","even/odd"],difficulty:"medium",time:15,url:"./labs-pack/division-cards-update/index.html",caPoints:[]},
  {id:"sx-division-with-and-without-remainder-update",title:"Division With and Without Remainder Update",emoji:"➗",grades:"Gr 3–5",topic:"Division",desc:"Division With and Without Remainder Update — interactive division lab",skills:["division","remainders","even/odd"],difficulty:"medium",time:15,url:"./labs-pack/division-with-and-without-remainder-update/index.html",caPoints:[]},
  {id:"sx-division-with-remainder",title:"Division With Remainder",emoji:"➗",grades:"Gr 3–5",topic:"Division",desc:"Division With Remainder — interactive division lab",skills:["division","remainders","even/odd"],difficulty:"medium",time:15,url:"./labs-pack/division-with-remainder/index.html",caPoints:[]},
  {id:"sx-egyptian",title:"Egyptian",emoji:"🏛️",grades:"Gr 3–7",topic:"Number Systems",desc:"Egyptian — interactive number systems lab",skills:["number systems","place value","numerals"],difficulty:"hard",time:15,url:"./labs-pack/egyptian/Egyptian account_ AVATAR_+GPT_RU+ верстка/index.html",caPoints:[]},
  {id:"sx-fractions-fix",title:"Fractions Fix",emoji:"🍕",grades:"Gr 3–6",topic:"Fractions",desc:"Fractions Fix — interactive fractions lab",skills:["fractions","numerator","denominator"],difficulty:"medium",time:15,url:"./labs-pack/fractions-fix/index.html",caPoints:[]},
  {id:"sx-fractions-mixed-numbers",title:"Fractions Mixed Numbers",emoji:"🍕",grades:"Gr 3–6",topic:"Fractions",desc:"Fractions Mixed Numbers — interactive fractions lab",skills:["fractions","numerator","denominator"],difficulty:"medium",time:15,url:"./labs-pack/fractions-mixed-numbers/fractions-mixed-numbers-xreadylab.html",caPoints:[]},
  {id:"sx-infinite-addition",title:"Infinite Addition",emoji:"➕",grades:"Gr 1–4",topic:"Addition & Subtraction",desc:"Infinite Addition — interactive addition & subtraction lab",skills:["addition","subtraction","mental math"],difficulty:"easy",time:15,url:"./labs-pack/infinite-addition/index.html",caPoints:[]},
  {id:"sx-lab-29",title:"Lab 29",emoji:"🧮",grades:"Gr 2–6",topic:"Math Practice",desc:"Lab 29 — interactive math practice lab",skills:["practice","fluency","speed"],difficulty:"medium",time:15,url:"./labs-pack/lab-29/square and triangular numbers/index.html",caPoints:[]},
  {id:"sx-lab-33",title:"Lab 33",emoji:"🧮",grades:"Gr 2–6",topic:"Math Practice",desc:"Lab 33 — interactive math practice lab",skills:["practice","fluency","speed"],difficulty:"medium",time:15,url:"./labs-pack/lab-33/index.html",caPoints:[]},
  {id:"sx-lab-37",title:"Lab 37",emoji:"🧮",grades:"Gr 2–6",topic:"Math Practice",desc:"Lab 37 — interactive math practice lab",skills:["practice","fluency","speed"],difficulty:"medium",time:15,url:"./labs-pack/lab-37/SummDocu/index.html",caPoints:[]},
  {id:"sx-lab-41",title:"Lab 41",emoji:"🧮",grades:"Gr 2–6",topic:"Math Practice",desc:"Lab 41 — interactive math practice lab",skills:["practice","fluency","speed"],difficulty:"medium",time:15,url:"./labs-pack/lab-41/1/index.html",caPoints:[]},
  {id:"sx-lab-42",title:"Lab 42",emoji:"🧮",grades:"Gr 2–6",topic:"Math Practice",desc:"Lab 42 — interactive math practice lab",skills:["practice","fluency","speed"],difficulty:"medium",time:15,url:"./labs-pack/lab-42/The tertiary system/index.html",caPoints:[]},
  {id:"sx-match-maker",title:"Match Maker",emoji:"🎯",grades:"Gr 1–4",topic:"Number Sense",desc:"Match Maker — interactive number sense lab",skills:["number sense","digit recognition"],difficulty:"easy",time:15,url:"./labs-pack/match-maker/match_maker/index.html",caPoints:[]},
  {id:"sx-multiplication",title:"Multiplication",emoji:"✖️",grades:"Gr 2–5",topic:"Multiplication",desc:"Multiplication — interactive multiplication lab",skills:["multiplication","arrays","fact fluency"],difficulty:"medium",time:15,url:"./labs-pack/multiplication/index.html",caPoints:[]},
  {id:"sx-multiplication-by-0",title:"Multiplication by 0",emoji:"✖️",grades:"Gr 2–5",topic:"Multiplication",desc:"Multiplication by 0 — interactive multiplication lab",skills:["multiplication","arrays","fact fluency"],difficulty:"medium",time:15,url:"./labs-pack/multiplication-by-0/index.html",caPoints:[]},
  {id:"sx-multiplication-by-1",title:"Multiplication by 1",emoji:"✖️",grades:"Gr 2–5",topic:"Multiplication",desc:"Multiplication by 1 — interactive multiplication lab",skills:["multiplication","arrays","fact fluency"],difficulty:"medium",time:15,url:"./labs-pack/multiplication-by-1/index.html",caPoints:[]},
  {id:"sx-multiplication-by-10",title:"Multiplication by 10",emoji:"✖️",grades:"Gr 2–5",topic:"Multiplication",desc:"Multiplication by 10 — interactive multiplication lab",skills:["multiplication","arrays","fact fluency"],difficulty:"medium",time:15,url:"./labs-pack/multiplication-by-10/index.html",caPoints:[]},
  {id:"sx-multiplication-cards",title:"Multiplication Cards",emoji:"✖️",grades:"Gr 2–5",topic:"Multiplication",desc:"Multiplication Cards — interactive multiplication lab",skills:["multiplication","arrays","fact fluency"],difficulty:"medium",time:15,url:"./labs-pack/multiplication-cards/index.html",caPoints:[]},
  {id:"sx-multiplication-of-simple-fractions",title:"Multiplication of Simple Fractions",emoji:"🍕",grades:"Gr 3–6",topic:"Fractions",desc:"Multiplication of Simple Fractions — interactive fractions lab",skills:["fractions","numerator","denominator"],difficulty:"medium",time:15,url:"./labs-pack/multiplication-of-simple-fractions/index.html",caPoints:[]},
  {id:"sx-multiplication-table",title:"Multiplication Table",emoji:"✖️",grades:"Gr 2–5",topic:"Multiplication",desc:"Multiplication Table — interactive multiplication lab",skills:["multiplication","arrays","fact fluency"],difficulty:"medium",time:15,url:"./labs-pack/multiplication-table/index.html",caPoints:[]},
  {id:"sx-negative-numbers",title:"Negative Numbers",emoji:"🔢",grades:"Gr 4–7",topic:"Number Operations",desc:"Negative Numbers — interactive number operations lab",skills:["operations","integers","decimals"],difficulty:"medium",time:15,url:"./labs-pack/negative-numbers/index.html",caPoints:[]},
  {id:"sx-negative-numbers-fix",title:"Negative Numbers Fix",emoji:"🔢",grades:"Gr 4–7",topic:"Number Operations",desc:"Negative Numbers Fix — interactive number operations lab",skills:["operations","integers","decimals"],difficulty:"medium",time:15,url:"./labs-pack/negative-numbers-fix/index.html",caPoints:[]},
  {id:"sx-new-fractions-2",title:"New Fractions 2",emoji:"🍕",grades:"Gr 3–6",topic:"Fractions",desc:"New Fractions 2 — interactive fractions lab",skills:["fractions","numerator","denominator"],difficulty:"medium",time:15,url:"./labs-pack/new-fractions-2/index.html",caPoints:[]},
  {id:"sx-new-fractions-2-ompare-deep",title:"New Fractions 2 Ompare Deep",emoji:"🍕",grades:"Gr 3–6",topic:"Fractions",desc:"New Fractions 2 Ompare Deep — interactive fractions lab",skills:["fractions","numerator","denominator"],difficulty:"medium",time:15,url:"./labs-pack/new-fractions-2-ompare-deep/index.html",caPoints:[]},
  {id:"sx-new-fractions-2-order",title:"New Fractions 2 Order",emoji:"🍕",grades:"Gr 3–6",topic:"Fractions",desc:"New Fractions 2 Order — interactive fractions lab",skills:["fractions","numerator","denominator"],difficulty:"medium",time:15,url:"./labs-pack/new-fractions-2-order/index.html",caPoints:[]},
  {id:"sx-rounding-up",title:"Rounding Up",emoji:"🔢",grades:"Gr 4–7",topic:"Number Operations",desc:"Rounding Up — interactive number operations lab",skills:["operations","integers","decimals"],difficulty:"medium",time:15,url:"./labs-pack/rounding-up/index.html",caPoints:[]},
  {id:"sx-summation-constellation",title:"Summation Constellation",emoji:"➕",grades:"Gr 1–4",topic:"Addition & Subtraction",desc:"Summation Constellation — interactive addition & subtraction lab",skills:["addition","subtraction","mental math"],difficulty:"easy",time:15,url:"./labs-pack/summation-constellation/subtraction/index.html",caPoints:[]},
  {id:"sx-text-division-tasks",title:"Text Division Tasks",emoji:"➗",grades:"Gr 3–5",topic:"Division",desc:"Text Division Tasks — interactive division lab",skills:["division","remainders","even/odd"],difficulty:"medium",time:15,url:"./labs-pack/text-division-tasks/index.html",caPoints:[]},
  {id:"sx-the-computer-code",title:"The Computer Code",emoji:"🏛️",grades:"Gr 3–7",topic:"Number Systems",desc:"The Computer Code — interactive number systems lab",skills:["number systems","place value","numerals"],difficulty:"hard",time:15,url:"./labs-pack/the-computer-code/index.html",caPoints:[]},
  {id:"sx-the-mosaic-of-multiplication",title:"The Mosaic of Multiplication",emoji:"✖️",grades:"Gr 2–5",topic:"Multiplication",desc:"The Mosaic of Multiplication — interactive multiplication lab",skills:["multiplication","arrays","fact fluency"],difficulty:"medium",time:15,url:"./labs-pack/the-mosaic-of-multiplication/index.html",caPoints:[]},
  {id:"sx-the-multiplication-blaster",title:"The Multiplication Blaster",emoji:"✖️",grades:"Gr 2–5",topic:"Multiplication",desc:"The Multiplication Blaster — interactive multiplication lab",skills:["multiplication","arrays","fact fluency"],difficulty:"medium",time:15,url:"./labs-pack/the-multiplication-blaster/index.html",caPoints:[]},
  {id:"sx-the-roman-account",title:"The Roman Account",emoji:"🏛️",grades:"Gr 3–7",topic:"Number Systems",desc:"The Roman Account — interactive number systems lab",skills:["number systems","place value","numerals"],difficulty:"hard",time:15,url:"./labs-pack/the-roman-account/index.html",caPoints:[]},
  {id:"sx-the-sum-of-even-and-odd-numbers",title:"The Sum of Even and Odd Numbers",emoji:"🎯",grades:"Gr 1–4",topic:"Number Sense",desc:"The Sum of Even and Odd Numbers — interactive number sense lab",skills:["number sense","digit recognition"],difficulty:"easy",time:15,url:"./labs-pack/the-sum-of-even-and-odd-numbers/index.html",caPoints:[]},
  {id:"sx-zero",title:"Zero",emoji:"0️⃣",grades:"Gr 1–3",topic:"Number Sense",desc:"Zero — interactive number sense lab",skills:["number sense","digit recognition"],difficulty:"easy",time:15,url:"./labs-pack/zero/index.html",caPoints:[]},

  // ── xreadylab.com web games (21 additional) ──
// xreadylab.com — Biology (5), Physics (8), Math (8 missing from labs-pack)
  {id:"xr-human-tissues",title:"Human Tissues",emoji:"🧬",grades:"Gr 7-12",topic:"Biology",subject:"Biology",desc:"Explore cell-level structure of human tissues — epithelial, connective, muscle, nervous.",skills:["biology","anatomy","cells"],difficulty:"medium",time:15,url:"https://xready.stemmy.io/Older/HumanTissues/",embed:true,caPoints:[]},
  {id:"xr-cardiac-cycle",title:"Cardiac Cycle",emoji:"❤️",grades:"Gr 8-12",topic:"Biology",subject:"Biology",desc:"Visualize the four phases of the cardiac cycle and pressure changes through the heart.",skills:["biology","physiology","heart"],difficulty:"medium",time:15,url:"https://xready.stemmy.io/Older/CardiacCycle/",embed:true,caPoints:[]},
  {id:"xr-hemostasis",title:"Hemostasis",emoji:"🩸",grades:"Gr 9-12",topic:"Biology",subject:"Biology",desc:"Understand how the body stops bleeding — platelets, coagulation cascade.",skills:["biology","blood","clotting"],difficulty:"hard",time:15,url:"https://xready.stemmy.io/Gemostaz/8895bcfb-03e4-4649-81f8-ee84fc57cb38/",embed:true,caPoints:[]},
  {id:"xr-nerve-impulse",title:"Nerve Impulse",emoji:"⚡",grades:"Gr 8-12",topic:"Biology",subject:"Biology",desc:"How neurons fire — action potentials, synapses, signal propagation.",skills:["biology","neurons","nervous system"],difficulty:"hard",time:15,url:"https://xready.stemmy.io/NervnaySistema/67680f29-6b09-4383-959d-7059eba68de8/",embed:true,caPoints:[]},
  {id:"xr-nerve-impulse-quiz",title:"Nerve Impulse Quiz",emoji:"🧠",grades:"Gr 8-12",topic:"Biology",subject:"Biology",desc:"Test knowledge of action potentials and synaptic transmission.",skills:["biology","assessment","nervous system"],difficulty:"medium",time:10,url:"https://xready.stemmy.io/NervnayaSistemaTrenajer/c27c725f-90f4-4d5c-9854-3030879b17da/",embed:true,caPoints:[]},
  {id:"xr-newtons-laws",title:"Newton's Laws",emoji:"🍎",grades:"Gr 6-12",topic:"Physics",subject:"Physics",desc:"Interactive demo of the three laws of motion.",skills:["physics","mechanics","forces"],difficulty:"medium",time:15,url:"https://xreadylab.com/public_html/wp-content/uploads/webgames/physics/Newton's laws/index.html",embed:true,caPoints:[]},
  {id:"xr-ohms-law",title:"Ohm's Law",emoji:"⚡",grades:"Gr 7-12",topic:"Physics",subject:"Physics",desc:"V = IR — explore voltage, current, resistance relationships.",skills:["physics","electricity","circuits"],difficulty:"medium",time:15,url:"https://xreadylab.com/public_html/wp-content/uploads/webgames/physics/Ohm's law/index.html",embed:true,caPoints:[]},
  {id:"xr-arcing-flight",title:"Arcing Flight",emoji:"🏹",grades:"Gr 8-12",topic:"Physics",subject:"Physics",desc:"Projectile motion — angle, velocity, range.",skills:["physics","projectiles","kinematics"],difficulty:"medium",time:15,url:"https://xreadylab.com/public_html/wp-content/uploads/webgames/physics/arcing flight/index.html",embed:true,caPoints:[]},
  {id:"xr-capacitors-1",title:"Capacitors #1",emoji:"🔋",grades:"Gr 9-12",topic:"Physics",subject:"Physics",desc:"Capacitor basics — charge, voltage, capacitance.",skills:["physics","electricity","capacitors"],difficulty:"hard",time:12,url:"https://xreadylab.com/public_html/wp-content/uploads/webgames/physics/Capacitors/10.6.1/index.html",embed:true,caPoints:[]},
  {id:"xr-capacitors-2",title:"Capacitors #2",emoji:"🔋",grades:"Gr 9-12",topic:"Physics",subject:"Physics",desc:"Series and parallel capacitor configurations.",skills:["physics","circuits"],difficulty:"hard",time:12,url:"https://xreadylab.com/public_html/wp-content/uploads/webgames/physics/Capacitors/10.6.2/index.html",embed:true,caPoints:[]},
  {id:"xr-capacitors-3",title:"Capacitors #3",emoji:"🔋",grades:"Gr 9-12",topic:"Physics",subject:"Physics",desc:"Energy stored in capacitors.",skills:["physics","energy"],difficulty:"hard",time:12,url:"https://xreadylab.com/public_html/wp-content/uploads/webgames/physics/Capacitors/10.6.3/index.html",embed:true,caPoints:[]},
  {id:"xr-capacitors-4",title:"Capacitors #4",emoji:"🔋",grades:"Gr 9-12",topic:"Physics",subject:"Physics",desc:"Discharging through resistance.",skills:["physics","RC circuits"],difficulty:"hard",time:12,url:"https://xreadylab.com/public_html/wp-content/uploads/webgames/physics/Capacitors/10.6.4/index.html",embed:true,caPoints:[]},
  {id:"xr-capacitors-5",title:"Capacitors #5",emoji:"🔋",grades:"Gr 9-12",topic:"Physics",subject:"Physics",desc:"Advanced capacitor problems.",skills:["physics","circuits"],difficulty:"hard",time:15,url:"https://xreadylab.com/public_html/wp-content/uploads/webgames/physics/Capacitors/10.6.5/index.html",embed:true,caPoints:[]},
  {id:"xr-subtraction",title:"Subtraction",emoji:"➖",grades:"Gr 1-3",topic:"Math",subject:"Math",desc:"Practice subtraction with interactive examples.",skills:["subtraction","arithmetic"],difficulty:"easy",time:10,url:"https://xreadylab.com/public_html/wp-content/uploads/webgames/math/subtraction/index.html",embed:true,caPoints:[]},
  {id:"xr-roman-numerals",title:"Roman Numeral System",emoji:"🏛️",grades:"Gr 3-6",topic:"Math",subject:"Math",desc:"Learn Roman numerals through interactive puzzles.",skills:["number systems","roman numerals"],difficulty:"medium",time:12,url:"https://xreadylab.com/public_html/wp-content/uploads/webgames/math/Roman Numeral System/index.html",embed:true,caPoints:[]},
  {id:"xr-ternary",title:"Ternary Number System",emoji:"🔢",grades:"Gr 5-9",topic:"Math",subject:"Math",desc:"Explore base-3 counting and conversions.",skills:["number systems","base conversion"],difficulty:"hard",time:12,url:"https://xreadylab.com/public_html/wp-content/uploads/webgames/math/Ternary Number System/index.html",embed:true,caPoints:[]},
  {id:"xr-binary",title:"Binary Number System",emoji:"💻",grades:"Gr 4-9",topic:"Math",subject:"Math",desc:"Understand how computers count in binary.",skills:["number systems","binary","computing"],difficulty:"medium",time:15,url:"https://xreadylab.com/public_html/wp-content/uploads/webgames/math/Binary Number System/index.html",embed:true,caPoints:[]},
  {id:"xr-area-model-mult",title:"Area Model Multiplication",emoji:"📐",grades:"Gr 3-5",topic:"Math",subject:"Math",desc:"Multiply using area models — visual partial products.",skills:["multiplication","area model"],difficulty:"medium",time:12,url:"https://xreadylab.com/public_html/wp-content/uploads/webgames/math/Area Model Multiplication/area-model-multiplication.html",embed:true,caPoints:[]},
  {id:"xr-decimal-fractions",title:"Decimal Fractions",emoji:"🍕",grades:"Gr 4-6",topic:"Math",subject:"Math",desc:"Convert between decimals and fractions.",skills:["decimals","fractions"],difficulty:"medium",time:12,url:"https://xreadylab.com/public_html/wp-content/uploads/webgames/math/decimal fractions/index.html",embed:true,caPoints:[]},
  {id:"xr-number-systems",title:"Number Systems (European & Indian)",emoji:"🌍",grades:"Gr 3-7",topic:"Math",subject:"Math",desc:"Compare historical number systems.",skills:["number systems","history of math"],difficulty:"medium",time:15,url:"https://xreadylab.com/public_html/wp-content/uploads/webgames/math/Number Systems European and Indian/index.html",embed:true,caPoints:[]},
  {id:"xr-equality-explorer",title:"Equality Explorer (Two Variables)",emoji:"⚖️",grades:"Gr 6-9",topic:"Math",subject:"Math",desc:"Balance equations with two unknowns — algebra prep.",skills:["algebra","equations"],difficulty:"hard",time:15,url:"https://xreadylab.com/public_html/wp-content/uploads/webgames/math/equality explorer. two variables/index.html",embed:true,caPoints:[]},
// Total new: 21 labs

  // ── KINDERGARTEN GAMES (Pre-K & K) ── built-in, mobile-first, with sound + tutor bridge ──
  {id:"k-count-critters",title:"Count the Critters",emoji:"🐰",grades:"Pre-K – K",topic:"Counting",subject:"Math",desc:"Count cute animals and tap the right number. Builds 1–10 number sense.",skills:["counting","number recognition","1-10"],difficulty:"easy",time:8,url:"./labs/count-critters.html",caPoints:["K.CC.A.1","K.CC.B.4"]},
  {id:"k-apple-math",title:"Apple Math",emoji:"🍎",grades:"Pre-K – 1",topic:"Addition",subject:"Math",desc:"Add apples in two baskets together — visual addition within 10.",skills:["addition","sums within 10","visual math"],difficulty:"easy",time:8,url:"./labs/apple-math.html",caPoints:["K.OA.A.1","K.OA.A.2"]},
  {id:"k-subtraction-garden",title:"Subtraction Garden",emoji:"🥕",grades:"Pre-K – 1",topic:"Subtraction",subject:"Math",desc:"A bunny picks carrots from the garden — how many are left? Subtraction within 10.",skills:["subtraction","differences within 10","take-away"],difficulty:"easy",time:8,url:"./labs/subtraction-garden.html",caPoints:["K.OA.A.1","K.OA.A.2","1.OA.C.6"]},
  {id:"k-number-hunt",title:"Number Hunt",emoji:"🔢",grades:"Pre-K – 1",topic:"Number recognition",subject:"Math",desc:"Hear a number 1–20 and find it in the grid. Builds teen-number recognition.",skills:["number recognition","numerals 1-20","teen numbers"],difficulty:"easy",time:6,url:"./labs/number-hunt.html",caPoints:["K.CC.A.3","K.NBT.A.1"]},
  {id:"k-greater-or-less",title:"Greater or Less",emoji:"⚖️",grades:"K – 1",topic:"Comparing",subject:"Math",desc:"Compare two groups of objects. Which is more? Less? Or equal?",skills:["comparing numbers","more less equal","quantity"],difficulty:"easy",time:6,url:"./labs/greater-or-less.html",caPoints:["K.CC.C.6","K.CC.C.7","1.NBT.B.3"]},
  {id:"k-shape-sort",title:"Shape Sort",emoji:"🔺",grades:"Pre-K – K",topic:"Geometry",subject:"Math",desc:"Drag shapes to their matching homes. Circles, squares, triangles, hearts, stars.",skills:["shapes","geometry","sorting","fine motor"],difficulty:"easy",time:6,url:"./labs/shape-sort.html",caPoints:["K.G.A.2","K.G.A.3"]},
  {id:"k-letter-match",title:"Letter Match",emoji:"🔤",grades:"Pre-K – K",topic:"Phonics",subject:"Reading",desc:"Hear a word and pick the letter that makes its first sound.",skills:["phonics","letter sounds","alphabet"],difficulty:"easy",time:8,url:"./labs/letter-match.html",caPoints:["RF.K.1.D","RF.K.2.D","RF.K.3.A"]},
  {id:"k-word-builder",title:"Word Builder",emoji:"🐱",grades:"K – 1",topic:"Phonics",subject:"Reading",desc:"Build 3-letter words like CAT, SUN, BUG by tapping letters in order. Foundational decoding.",skills:["CVC words","decoding","blending","phonics"],difficulty:"medium",time:10,url:"./labs/word-builder.html",caPoints:["RF.K.2.D","RF.K.3.B","RF.1.2.B"]},
  {id:"k-sight-words",title:"Sight Words",emoji:"🌟",grades:"K – 1",topic:"Reading",subject:"Reading",desc:"Hear high-frequency words (Dolch pre-K/K list) and find them by sight. Builds fluency.",skills:["sight words","Dolch words","fluency","reading"],difficulty:"medium",time:8,url:"./labs/sight-words.html",caPoints:["RF.K.3.C","RF.1.3.G"]},
  {id:"k-rhyme-time",title:"Rhyme Time",emoji:"🎵",grades:"Pre-K – K",topic:"Reading",subject:"Reading",desc:"Hear a word and pick another word that rhymes with it. Phonological awareness.",skills:["rhyming","phonological awareness","word families"],difficulty:"easy",time:8,url:"./labs/rhyme-time.html",caPoints:["RF.K.2.A"]},
  {id:"k-pattern-play",title:"Pattern Play",emoji:"🌈",grades:"Pre-K – 1",topic:"Patterns",subject:"Math",desc:"Look at a colorful pattern and pick what comes next. AB, AAB, ABB patterns.",skills:["patterns","logic","sequencing"],difficulty:"easy",time:6,url:"./labs/pattern-play.html",caPoints:["K.MD.B.3"]},
  // ── K/1 second batch — time, skip counting, place value, letter case, syllables, sentences ──
  {id:"k-clock-oclock",title:"Clock O'Clock",emoji:"🕐",grades:"K – 1",topic:"Time",subject:"Math",desc:"Read an analog clock on the hour. The short hand points to the hour — which number is it on?",skills:["telling time","analog clock","hour"],difficulty:"medium",time:8,url:"./labs/clock-oclock.html",caPoints:["1.MD.B.3"]},
  {id:"k-skip-count",title:"Skip Count",emoji:"🦘",grades:"K – 1",topic:"Counting",subject:"Math",desc:"Count by 2s, 5s, and 10s. Fill in the missing number in the hopping sequence.",skills:["skip counting","2s 5s 10s","sequencing"],difficulty:"medium",time:8,url:"./labs/skip-count.html",caPoints:["1.OA.C.5","2.NBT.A.2"]},
  {id:"k-tens-and-ones",title:"Tens & Ones",emoji:"🔟",grades:"1",topic:"Place value",subject:"Math",desc:"Count base-10 sticks and ones. Foundation for understanding numbers 11–99.",skills:["place value","tens and ones","base-10","two-digit numbers"],difficulty:"medium",time:10,url:"./labs/tens-and-ones.html",caPoints:["1.NBT.B.2","1.NBT.B.3"]},
  {id:"k-big-and-small-letters",title:"Big & Small Letters",emoji:"🅰️",grades:"Pre-K – K",topic:"Phonics",subject:"Reading",desc:"Match uppercase letters to their lowercase partners. Includes the tricky b/d/p/q pairs.",skills:["letter recognition","uppercase lowercase","alphabet"],difficulty:"easy",time:6,url:"./labs/big-and-small-letters.html",caPoints:["RF.K.1.D"]},
  {id:"k-syllable-clap",title:"Syllable Clap",emoji:"🥁",grades:"Pre-K – 1",topic:"Reading",subject:"Reading",desc:"Hear a word and count the syllables (the beats). Cat = 1. Mon-key = 2. Ba-na-na = 3.",skills:["syllables","phonological awareness","beats"],difficulty:"easy",time:8,url:"./labs/syllable-clap.html",caPoints:["RF.K.2.B"]},
  {id:"k-sentence-builder",title:"Sentence Builder",emoji:"🪄",grades:"K – 1",topic:"Writing",subject:"Reading",desc:"Tap word tiles to build a sentence about a picture. Starts with a CAPITAL letter and ends with a period.",skills:["sentence structure","capitalization","punctuation","word order"],difficulty:"medium",time:10,url:"./labs/sentence-builder.html",caPoints:["L.K.2","L.K.1.F","L.1.2"]},
  // ── K/1 batch 4 — money, measurement, fractions, science (NGSS), social studies, ending sounds ──
  {id:"k-coin-counter",title:"Coin Counter",emoji:"💰",grades:"1 – 2",topic:"Money",subject:"Math",desc:"Count pennies, nickels, dimes, and quarters. How much money is here?",skills:["money","coins","counting by 5s and 10s","cents"],difficulty:"medium",time:10,url:"./labs/coin-counter.html",caPoints:["2.MD.C.8","1.MD"]},
  {id:"k-measure-it",title:"Measure It",emoji:"📏",grades:"K – 1",topic:"Measurement",subject:"Math",desc:"Measure how long an object is using unit cubes. Counting + length.",skills:["measurement","length","non-standard units","counting"],difficulty:"easy",time:7,url:"./labs/measure-it.html",caPoints:["K.MD.A.1","1.MD.A.2"]},
  {id:"k-fraction-pizza",title:"Fraction Pizza",emoji:"🍕",grades:"1 – 2",topic:"Fractions",subject:"Math",desc:"Halves, thirds, and quarters — what fraction of the pizza is shaded?",skills:["fractions","halves","quarters","equal parts"],difficulty:"medium",time:8,url:"./labs/fraction-pizza.html",caPoints:["1.G.A.3","2.G.A.3"]},
  {id:"k-five-senses",title:"Five Senses",emoji:"👀",grades:"Pre-K – 1",topic:"Science",subject:"Science",desc:"See, hear, smell, taste, touch — which sense do you use? Intro to the human body.",skills:["five senses","body","observation","science"],difficulty:"easy",time:7,url:"./labs/five-senses.html",caPoints:["K-LS1-1","K-PS"]},
  {id:"k-weather-watch",title:"Weather Watch",emoji:"🌦️",grades:"Pre-K – 1",topic:"Science",subject:"Science",desc:"Name the weather and pick what to wear. Earth science + daily observation.",skills:["weather","seasons","earth science","observation"],difficulty:"easy",time:7,url:"./labs/weather-watch.html",caPoints:["K-ESS2-1"]},
  {id:"k-animal-homes",title:"Animal Homes",emoji:"🐾",grades:"K – 2",topic:"Science",subject:"Science",desc:"Match animals to their habitats — ocean, forest, farm, jungle, arctic, desert.",skills:["habitats","animals","life science","classification"],difficulty:"easy",time:8,url:"./labs/animal-homes.html",caPoints:["2-LS4-1","K-LS1-1"]},
  {id:"k-ending-sounds",title:"Ending Sounds",emoji:"🔚",grades:"K – 1",topic:"Phonics",subject:"Reading",desc:"Hear a word and pick the letter for its LAST sound. Pairs with Letter Match (first sounds).",skills:["phonics","ending sounds","letter sounds","decoding"],difficulty:"medium",time:8,url:"./labs/ending-sounds.html",caPoints:["RF.K.2.D","RF.K.3.A"]},
  {id:"k-community-helpers",title:"Community Helpers",emoji:"🚒",grades:"Pre-K – 1",topic:"Social Studies",subject:"Social Studies",desc:"Meet the people who help our community — firefighters, doctors, teachers — and the tools they use.",skills:["community","social studies","jobs","helpers"],difficulty:"easy",time:7,url:"./labs/community-helpers.html",caPoints:["Social Studies K.3"]},
];


export const TUTORS = [
  // ── CORE SUBJECTS ──────────────────────────────────────────────────────────
  {id:"math",      ages:"K–12",  label:"Math",             emoji:"🔢",color:"#d9622b",bg:"#fde8d8",name:"Ms. Ada",    bio:"MIT math researcher. Makes numbers feel like play.",        tool:"Khan Academy + Zearn + Happy Numbers",
   starters:["I'm stuck on this problem","Explain fractions to me","What's a fun way to learn multiplication?","Help me understand negative numbers"],
   system:`You are Ms. Ada, math tutor at Neoschool. Socratic method — never give direct answers, guide discovery. Adapt your language to the student's grade: very simple and visual for K-2, more abstract for older grades. Always use real-world analogies. 2-3 sentences. Warm and encouraging.`},
  {id:"reading",   ages:"K–8",   label:"Reading & ELA",    emoji:"📖",color:"#2d6ea8",bg:"#ddeeff",name:"Mr. Miles",  bio:"Published children's author and reading specialist.",        tool:"CommonLit + ReadWorks + Starfall",
   starters:["I don't understand what I read","How do I write a better story?","What is a main idea?","Help me with spelling"],
   system:`You are Mr. Miles, reading and writing tutor at Neoschool. Adapt to age: for K-2 use phonics, letter sounds, and simple sentence building; for 3-5 focus on comprehension and paragraph writing; for 6+ tackle literary analysis. Socratic method. 2-3 sentences. Encouraging and imaginative.`},
  {id:"writing",   ages:"K–12",  label:"Creative Writing",  emoji:"✍️",color:"#9c5ab5",bg:"#f3e8ff",name:"Ms. Quill",  bio:"Author of 3 children's books. Loves story structure.",       tool:"Storybird + Google Docs",
   starters:["Help me start my story","I don't know what to write about","How do I make my characters more interesting?","What's a good story ending?"],
   system:`You are Ms. Quill, creative writing tutor at Neoschool. For young writers (K-2) use 'story starter' prompts and drawing connections; for older students explore character, conflict, and voice. Ask "what happens next?" before "what should happen?" 2-3 sentences. Playful and imaginative.`},
  {id:"science",   ages:"K–12",  label:"Science",           emoji:"🔬",color:"#4a7c6a",bg:"#dff2ea",name:"Dr. Nova",   bio:"Astrophysicist turned educator. Brings wonder to learning.", tool:"PhET Simulations + CK-12",
   starters:["Why is the sky blue?","How do plants make food?","What causes earthquakes?","Explain gravity to me"],
   system:`You are Dr. Nova, science tutor at Neoschool. Use inquiry-based learning — always ask a guiding question before explaining. For K-2 use nature observations and simple experiments; for older grades introduce hypothesis and evidence. Reference PhET simulations. 2-3 sentences. Filled with wonder.`},
  {id:"history",   ages:"2–12",  label:"History & Social Studies",emoji:"🏛️",color:"#b5651d",bg:"#fdf0e0",name:"Prof. Arlo", bio:"Living-history enthusiast. Makes the past feel immediate.",  tool:"iCivics + Newsela",
   starters:["Why do we study history?","Tell me about ancient Egypt","What caused World War II?","How did people live 100 years ago?"],
   system:`You are Professor Arlo, history tutor at Neoschool. Make history personal: "imagine you were there." For K-2 use stories and people; for older grades explore cause, effect, and perspective. Ask "why do you think that happened?" never just recite facts. 2-3 sentences. Storytelling tone.`},
  {id:"geography", ages:"K–8",   label:"Geography & World", emoji:"🌏",color:"#2e8b57",bg:"#e0f5ea",name:"Explorer Mia",bio:"Travel photographer. Has visited 70 countries.",            tool:"Google Earth + National Geographic Kids",
   starters:["Where is [country]?","What is a continent?","How are mountains formed?","Tell me about a cool place"],
   system:`You are Explorer Mia, geography tutor at Neoschool. Connect places to stories and cultures. For K-2 use local geography and basic maps; for older students explore physical geography, culture, and current events. Ask "what do you already know about this place?" 2-3 sentences. Adventurous.`},
  {id:"cs",        ages:"K–12",  label:"Coding & CS",       emoji:"💻",color:"#7c4a9a",bg:"#f0e8ff",name:"Coach Rex",  bio:"Former Google engineer. Believes every kid is a builder.", tool:"Code.org + Scratch + Python",
   starters:["What is a variable?","How do loops work?","I want to make a game","Help me debug my code"],
   system:`You are Coach Rex, coding mentor at Neoschool. For K-2 use unplugged activities and Scratch Jr; for 3-5 use Scratch blocks; for 6+ introduce text-based code. Teach computational thinking through building. Guide debugging with questions. 2-3 sentences. Enthusiastic.`},
  // ── LANGUAGES ─────────────────────────────────────────────────────────────
  {id:"spanish",   ages:"Pre-K–8",label:"Spanish",          emoji:"🇪🇸",color:"#c0392b",bg:"#fde8e8",name:"Señora Luna",bio:"Native speaker. Teaches through songs and stories.",        tool:"Duolingo + Conjuguemos",
   starters:["Teach me some Spanish words","How do I say 'I am hungry'?","¿Cómo estás?","What are colors in Spanish?"],
   system:`You are Señora Luna, Spanish tutor at Neoschool. Immersive method — weave Spanish words naturally into responses. For Pre-K/K use songs, colors, numbers, animals; for older students build sentences and grammar. Always teach through context, not translation lists. 2-3 sentences. Warm and musical.`},
  {id:"langs",     ages:"K–12",  label:"World Languages",   emoji:"🌍",color:"#e74c3c",bg:"#fde8e8",name:"Maestro Luca",bio:"Polyglot who speaks 7 languages. Language opens doors.",    tool:"Duolingo + Digital Dialects",
   starters:["I want to learn French","How do you say hello in Japanese?","What's the hardest language to learn?","Teach me a phrase"],
   system:`You are Maestro Luca, world languages tutor at Neoschool. You can teach any language. Start with greetings and practical phrases. Mix target language into responses naturally. Connect language to culture. For young learners use songs and games. 2-3 sentences. Enthusiastic polyglot energy.`},
  // ── ARTS ───────────────────────────────────────────────────────────────────
  {id:"arts",      ages:"Pre-K–12",label:"Visual Arts",     emoji:"🎨",color:"#d4a012",bg:"#fdf3d0",name:"Studio Kai", bio:"Award-winning designer. Makes every child feel like an artist.",tool:"Canva + Adobe Express",
   starters:["How do I draw better?","What are the primary colors?","What is composition?","Help me design a poster"],
   system:`You are Studio Kai, visual arts tutor at Neoschool. For Pre-K/K focus on color, shape, texture and free exploration; for older students introduce design principles, art history, and critique. Always ask "what do you see?" before explaining. 2-3 sentences. Visually descriptive.`},
  {id:"music",     ages:"K–12",  label:"Music",             emoji:"🎵",color:"#0a7c8a",bg:"#d4f0f4",name:"Maestro Finn",bio:"Jazz musician and Orff-trained music teacher.",             tool:"Chrome Music Lab + MusicFirst",
   starters:["What is a music note?","Teach me to read music","What's the difference between fast and slow?","How do instruments make sound?"],
   system:`You are Maestro Finn, music tutor at Neoschool. For K-2 use rhythm, body percussion, and listening games; for older students introduce notation, theory, and music history. Ask students to clap or hum patterns. Reference Chrome Music Lab for interactive exploration. 2-3 sentences. Rhythmic and warm.`},
  // ── ELEMENTARY-SPECIFIC ───────────────────────────────────────────────────
  {id:"phonics",   ages:"Pre-K–2",label:"Phonics & Early Reading",emoji:"🔤",color:"#ff6b9d",bg:"#ffe8f3",name:"Ms. Sunny", bio:"Early childhood specialist. Loves letter sounds and rhymes.", tool:"Starfall + Phonics Hero",
   starters:["What sound does the letter B make?","How do I read this word?","What rhymes with cat?","I'm learning to read"],
   system:`You are Ms. Sunny, phonics and early reading tutor at Neoschool. Use simple, playful language. Focus on letter sounds, blending, and sight words. Use rhymes, alliteration, and clapping syllables. Always celebrate effort. Never more than 1-2 very simple sentences. Bright and cheerful energy.`},
  {id:"earlymath", ages:"Pre-K–2",label:"Early Math",        emoji:"🔵",color:"#ff8c42",bg:"#fff0e6",name:"Count Milo", bio:"Former kindergarten teacher. Turns counting into adventure.", tool:"Happy Numbers + MathSeeds",
   starters:["I'm learning to count","What comes after 10?","Help me with shapes","How do I add?"],
   system:`You are Count Milo, early math tutor at Neoschool. Designed for Pre-K through 2nd grade. Use objects, fingers, and stories to explain numbers. Talk about counting bears, stacking blocks, sharing cookies. Keep language extremely simple — one idea at a time. 1-2 sentences max. Bouncy, fun energy.`},
  // ── ENRICHMENT ────────────────────────────────────────────────────────────
  {id:"logic",     ages:"K–12",  label:"Critical Thinking", emoji:"🧩",color:"#5b4fcf",bg:"#eeebff",name:"Dr. Logic",  bio:"Puzzle designer and former debate coach.",                 tool:"Brilliant.org + BrainPOP",
   starters:["Give me a brain teaser","How do I solve this logic puzzle?","What is a hypothesis?","Teach me to argue better"],
   system:`You are Dr. Logic, critical thinking tutor at Neoschool. Present puzzles and paradoxes. Ask "what's your reasoning?" Guide students to find holes in arguments, including your own. For K-2 use simple pattern puzzles; for older students introduce formal logic and fallacies. 2-3 sentences. Playfully challenging.`},
  {id:"finance",   ages:"2–12",  label:"Money & Finance",   emoji:"💰",color:"#27ae60",bg:"#e0f5ea",name:"Coach Cash",  bio:"Financial educator who simplifies money for kids.",         tool:"EVERFI + Practical Money Skills",
   starters:["What is money?","How do I save up for something?","What is a budget?","How do banks work?"],
   system:`You are Coach Cash, financial literacy tutor at Neoschool. For K-2 use coins, piggy banks, and simple needs vs wants; for older students introduce budgeting, interest, and entrepreneurship. Make money math real: "if you earn $5/week, how many weeks to save for a $25 game?" 2-3 sentences. Practical and encouraging.`},
  {id:"nature",    ages:"Pre-K–8",label:"Nature & Environment",emoji:"🌿",color:"#3a7d44",bg:"#e8f5e9",name:"Ranger Jo",  bio:"Wilderness guide and naturalist educator.",                tool:"iNaturalist + National Geographic Kids",
   starters:["What is photosynthesis?","Tell me about animals","How does weather work?","Why do leaves change color?"],
   system:`You are Ranger Jo, nature and environment tutor at Neoschool. Connect every concept to something students can observe outside. For Pre-K/K use animals, plants, weather; for older students explore ecosystems, climate, and conservation. Ask "have you ever seen...?" 2-3 sentences. Grounded and observational.`},
  {id:"philosophy",ages:"3–12",  label:"Philosophy & Big Ideas",emoji:"🤔",color:"#6c5ce7",bg:"#f0edff",name:"Sage",      bio:"Philosophy PhD who believes kids ask the best questions.", tool:"Philosophy for Children (P4C)",
   starters:["Is lying always wrong?","What is fairness?","Do animals have feelings?","Why do we exist?"],
   system:`You are Sage, philosophy tutor at Neoschool. Never give answers to philosophical questions — explore them together. Use thought experiments and "what if" scenarios. For younger students use simple fairness stories; for older students introduce Socratic dialogue. 2-3 sentences. Wonder-filled and non-judgmental.`},
  {id:"pe",        ages:"Pre-K–8",label:"Physical Education", emoji:"⚽",color:"#e84393",bg:"#ffe8f3",name:"Coach Spark", bio:"PE teacher and sports scientist. Movement is medicine.",   tool:"GoNoodle + Fitness Blender",
   starters:["How do I get better at sports?","What is a warm-up?","Teach me a new game","Why is exercise important?"],
   system:`You are Coach Spark, PE and movement tutor at Neoschool. Combine fitness science with fun. For Pre-K/K suggest movement games, dance, and animal walks; for older students discuss training, sports skills, and health. Always ask about their favorite ways to move. 2-3 sentences. High energy.`},
  {id:"sel",       ages:"Pre-K–12",label:"Life Skills & SEL",emoji:"❤️",color:"#4a7c6a",bg:"#dff2ea",name:"Ms. River",  bio:"Licensed counselor and mindfulness coach.",               tool:"EVERFI + Second Step",
   starters:["I'm feeling stressed","How do I deal with a difficult friend?","What is mindfulness?","How do I focus better?"],
   system:`You are Ms. River, social-emotional learning coach at Neoschool. Validate feelings first, then gently guide reflection. For young children use simple emotion words and breathing exercises; for older students explore identity, resilience, and relationship skills. Never rush to solutions. 2-3 sentences. Warm and non-judgmental.`},
];


export const LAB_TUTORS = {
  "multiplication-blaster": {name:"Ms. Ada",system:`You are Ms. Ada tutoring a student using Multiplication Blaster. They're building matrices by shooting paintballs to understand multiplication. You can see their session — guide them with questions about what patterns they notice in the arrays. Ask things like "If you shoot 3 rows of 4, what do you notice about the total?" Never give the answer directly. 2-3 sentences, warm.`},
  "division-cards": {name:"Ms. Ada",system:`You are Ms. Ada tutoring a student using Division Cards. They're practicing division with timed flashcards. Guide them to discover shortcuts and patterns. Ask things like "What relationship do you notice between 20÷4 and 20÷5?" 2-3 sentences.`},
  "fractions-basic": {name:"Ms. Ada",system:`You are Ms. Ada tutoring with Fractions Basics. The student is visualizing fractions as parts of a whole. Ask questions like "If you have 3/4 of a pizza, how many slices are eaten?" Guide discovery. 2-3 sentences.`},
  "fractions-order": {name:"Ms. Ada",system:`You are Ms. Ada tutoring with Ordering Fractions. Guide the student to find strategies for comparing fractions. Ask "Is 2/3 closer to 1/2 or to 1? How do you know?" 2-3 sentences.`},
  "negative-numbers": {name:"Ms. Ada",system:`You are Ms. Ada tutoring with Negative Numbers. Use real-world analogies like temperature or money. Ask "If it's -3 degrees and drops 4 more degrees, how would you show that?" 2-3 sentences.`},
  "commutative": {name:"Ms. Ada",system:`You are Ms. Ada tutoring with Commutative Property. Ask "Why do you think 4×3 gives the same answer as 3×4? What does the matrix look like if you rotate it?" 2-3 sentences.`},
  "column-addition": {name:"Ms. Ada",system:`You are Ms. Ada tutoring with Column Addition. Focus on place value understanding. Ask "What does the 1 that carries over to the tens place represent?" 2-3 sentences.`},
  "division-remainder": {name:"Ms. Ada",system:`You are Ms. Ada tutoring with Division & Remainders. Ask "If you have 17 cookies and 4 friends, how many does each get? What happens to the leftover?" 2-3 sentences.`},
  "multiply-by-1": {name:"Ms. Ada",system:`You are Ms. Ada tutoring with Multiply by 1. Ask "What happens when you scale something by 1? Can you think of a real-life example where multiplying by 1 keeps things the same?" 2-3 sentences.`},
  "multiplication": {name:"Ms. Ada",system:`You are Ms. Ada tutoring with Multiplication Lab. Guide from arrays to abstract. Ask "Can you explain multiplication as repeated addition using this dot grid?" 2-3 sentences.`},
  "rounding": {name:"Ms. Ada",system:`You are Ms. Ada tutoring with Rounding Numbers. Ask "Why might an engineer need to round? When would rounding give you the wrong answer?" 2-3 sentences.`},
  "multiplication-cards": {name:"Ms. Ada",system:`You are Ms. Ada tutoring with Multiplication Cards. Help build fluency strategies. Ask "For 8×7, do you have a trick to remember it, or do you build it from something you know?" 2-3 sentences.`},
  "bubbles": {name:"Ms. Ada",system:`You are Ms. Ada tutoring with Math Bubbles. The student is practicing quick arithmetic. Ask "What mental tricks help you add quickly? Can you break 7+8 into easier parts?" 2-3 sentences.`},
  "even-odd-sum": {name:"Ms. Ada",system:`You are Ms. Ada tutoring with Even & Odd Sums. Guide pattern discovery. Ask "Will odd + odd always be even? Can you test it with several examples to prove it?" 2-3 sentences.`},
};

export const CONTENT_PROVIDERS = [
  {id:"khan",name:"Khan Academy",emoji:"📐",desc:"Free K-12 math, science, computing",api:"khanacademy.org/api/v1",status:"free",subjects:["math","science","cs"],integration:"SSO + Progress API",active:true},
  {id:"zearn",name:"Zearn Math",emoji:"🔢",desc:"Full Eureka Math curriculum K-8",api:"zearn.org",status:"free",subjects:["math"],integration:"Google Classroom",active:true},
  {id:"commonlit",name:"CommonLit",emoji:"📚",desc:"Free ELA curriculum Gr 3-12",api:"commonlit.org",status:"free",subjects:["reading","writing"],integration:"Clever SSO",active:true},
  {id:"phet",name:"PhET Simulations",emoji:"⚗️",desc:"125+ free STEM simulations",api:"phet.colorado.edu",status:"free",subjects:["science","math"],integration:"HTML5 embed",active:true},
  {id:"geogebra",name:"GeoGebra",emoji:"📊",desc:"Interactive math tools & graphing",api:"geogebra.org/api",status:"free",subjects:["math"],integration:"API + embed",active:true},
  {id:"scratch",name:"Scratch",emoji:"🐱",desc:"Creative coding MIT platform",api:"api.scratch.mit.edu",status:"free",subjects:["cs","arts"],integration:"Public API",active:true},
  {id:"code",name:"Code.org",emoji:"🤖",desc:"CS education K-12",api:"studio.code.org",status:"free",subjects:["cs"],integration:"Embed",active:true},
  {id:"duolingo",name:"Duolingo for Schools",emoji:"🌍",desc:"40+ languages free for schools",api:"schools.duolingo.com",status:"free",subjects:["languages"],integration:"Schools Portal",active:true},
  {id:"canva",name:"Canva Education",emoji:"🎨",desc:"Free Pro for K-12",api:"canva.com/education",status:"free",subjects:["arts","design"],integration:"OAuth",active:true},
  {id:"happynumbers",name:"Happy Numbers",emoji:"😊",desc:"Adaptive K-5 math",api:"happynumbers.com",status:"paid",subjects:["math"],integration:"API available",active:false},
  {id:"amira",name:"Amira Learning",emoji:"📖",desc:"AI reading tutor speech recognition",api:"amiralearning.com",status:"paid",subjects:["reading"],integration:"District SSO",active:false},
  {id:"ck12",name:"CK-12",emoji:"📓",desc:"Free adaptive STEM textbooks",api:"ck12.org/api",status:"free",subjects:["science","math"],integration:"Open API",active:true},
  {id:"desmos",name:"Desmos",emoji:"📈",desc:"Graphing calculator & math activities",api:"desmos.com/api",status:"free",subjects:["math"],integration:"JS API",active:true},
  {id:"everfi",name:"EVERFI",emoji:"🌱",desc:"Life skills, financial literacy",api:"everfi.com",status:"free",subjects:["sel","life skills"],integration:"School Portal",active:true},
];


export const DEMO_STUDENTS = [
  {id:"s1",name:"Ava Chen",grade:"3rd Grade",age:8,color:"#4a7c6a",init:"AC",city:"Berkeley",labProgress:{"multiplication-blaster":72,"fractions-basic":45,"division-cards":88},totalMins:312,streak:7,velocity:"steady",alerts:[{msg:"Stalled on fractions 9 min",sev:"high"}]},
  {id:"s2",name:"Marcus Johnson",grade:"2nd Grade",age:7,color:"#d9622b",init:"MJ",city:"Oakland",labProgress:{"multiplication-blaster":95,"multiplication-cards":88,"bubbles":92},totalMins:428,streak:12,velocity:"accelerating",alerts:[]},
  {id:"s3",name:"Sofia Martinez",grade:"4th Grade",age:9,color:"#2d6ea8",init:"SM",city:"Fremont",labProgress:{"fractions-order":70,"fractions-basic":90,"negative-numbers":30},totalMins:380,streak:5,velocity:"plateauing",alerts:[{msg:"ELA engagement low this week",sev:"medium"}]},
  {id:"s4",name:"Ethan Park",grade:"3rd Grade",age:8,color:"#7c4a9a",init:"EP",city:"San Jose",labProgress:{"commutative":97,"column-addition":75,"rounding":60},totalMins:356,streak:9,velocity:"steady",alerts:[]},
  {id:"s5",name:"Lily Thompson",grade:"1st Grade",age:6,color:"#c94040",init:"LT",city:"Sacramento",labProgress:{"bubbles":55,"even-odd-sum":48,"multiplication-cards":30},totalMins:168,streak:3,velocity:"foundational",alerts:[{msg:"New student — getting started",sev:"info"}]},
];


export const TOOLS = [
  // ── PhET Interactive Simulations (open source, freely embeddable) ──────────
  {id:"phet-fractions",     cat:"PhET · Math",   emoji:"🍕", label:"Fraction Matcher",        grades:"Gr 3–5",  subject:"Math",    color:"#e05c3a",
   desc:"Match fraction shapes and numbers to build understanding. Nobel Prize–backed simulation.",
   url:"https://phet.colorado.edu/sims/html/fraction-matcher/latest/fraction-matcher_all.html",
   embed:true, github:"https://github.com/phetsims/fraction-matcher"},
  {id:"phet-build-fraction",cat:"PhET · Math",   emoji:"🧱", label:"Build a Fraction",         grades:"Gr 3–5",  subject:"Math",    color:"#e05c3a",
   desc:"Build fractions from shapes and numbers by matching equal parts.",
   url:"https://phet.colorado.edu/sims/html/build-a-fraction/latest/build-a-fraction_all.html",
   embed:true, github:"https://github.com/phetsims/build-a-fraction"},
  {id:"phet-area",          cat:"PhET · Math",   emoji:"⬛", label:"Area Model Multiplication", grades:"Gr 3–6",  subject:"Math",    color:"#e05c3a",
   desc:"Visualize multiplication as area. Connect arrays to abstract notation.",
   url:"https://phet.colorado.edu/sims/html/area-model-multiplication/latest/area-model-multiplication_all.html",
   embed:true, github:"https://github.com/phetsims/area-model-multiplication"},
  {id:"phet-arithmetic",    cat:"PhET · Math",   emoji:"✖️", label:"Arithmetic",               grades:"Gr 2–5",  subject:"Math",    color:"#e05c3a",
   desc:"Practice multiplication, division, and factoring with visual games.",
   url:"https://phet.colorado.edu/sims/html/arithmetic/latest/arithmetic_all.html",
   embed:true, github:"https://github.com/phetsims/arithmetic"},
  {id:"phet-number-line",   cat:"PhET · Math",   emoji:"📏", label:"Number Line Operations",   grades:"Gr 5–7",  subject:"Math",    color:"#e05c3a",
   desc:"Add and subtract integers on an interactive number line.",
   url:"https://phet.colorado.edu/sims/html/number-line-operations/latest/number-line-operations_all.html",
   embed:true, github:"https://github.com/phetsims/number-line-operations"},
  {id:"phet-waves",         cat:"PhET · Science",emoji:"〰️", label:"Wave on a String",         grades:"Gr 5–9",  subject:"Science", color:"#2d6ea8",
   desc:"Explore wave properties: frequency, amplitude, reflection.",
   url:"https://phet.colorado.edu/sims/html/wave-on-a-string/latest/wave-on-a-string_all.html",
   embed:true, github:"https://github.com/phetsims/wave-on-a-string"},
  {id:"phet-forces",        cat:"PhET · Science",emoji:"💪", label:"Forces and Motion",        grades:"Gr 4–8",  subject:"Science", color:"#2d6ea8",
   desc:"Push objects and see how forces affect motion. Newton's laws made visual.",
   url:"https://phet.colorado.edu/sims/html/forces-and-motion-basics/latest/forces-and-motion-basics_all.html",
   embed:true, github:"https://github.com/phetsims/forces-and-motion-basics"},
  {id:"phet-gravity",       cat:"PhET · Science",emoji:"🪐", label:"Gravity and Orbits",       grades:"Gr 5–9",  subject:"Science", color:"#2d6ea8",
   desc:"Move the sun, earth, moon and space station to see orbital effects.",
   url:"https://phet.colorado.edu/sims/html/gravity-and-orbits/latest/gravity-and-orbits_all.html",
   embed:true, github:"https://github.com/phetsims/gravity-and-orbits"},
  {id:"phet-atom",          cat:"PhET · Science",emoji:"⚛️", label:"Build an Atom",            grades:"Gr 5–9",  subject:"Science", color:"#2d6ea8",
   desc:"Build atoms from protons, neutrons, and electrons. Discover isotopes.",
   url:"https://phet.colorado.edu/sims/html/build-an-atom/latest/build-an-atom_all.html",
   embed:true, github:"https://github.com/phetsims/build-an-atom"},
  // ── GeoGebra (freely embeddable) ──────────────────────────────────────────
  {id:"ggb-graphing",       cat:"GeoGebra",      emoji:"📈", label:"Graphing Calculator",      grades:"Gr 6–12", subject:"Math",    color:"#7c4a9a",
   desc:"Plot functions, find intersections, trace curves. Full-featured graphing.",
   url:"https://www.geogebra.org/graphing?embed",
   embed:true, github:"https://github.com/geogebra/geogebra"},
  {id:"ggb-geometry",       cat:"GeoGebra",      emoji:"📐", label:"Interactive Geometry",     grades:"Gr 4–10", subject:"Math",    color:"#7c4a9a",
   desc:"Construct and explore geometric shapes, angles, and proofs interactively.",
   url:"https://www.geogebra.org/geometry?embed",
   embed:true},
  {id:"ggb-classic",        cat:"GeoGebra",      emoji:"🔢", label:"GeoGebra Classic",         grades:"Gr 6–12", subject:"Math",    color:"#7c4a9a",
   desc:"Full algebra + geometry + spreadsheet + CAS in one window.",
   url:"https://www.geogebra.org/classic?embed",
   embed:true},
  // ── Desmos (freely embeddable) ────────────────────────────────────────────
  {id:"desmos-calc",        cat:"Desmos",        emoji:"🖩",  label:"Desmos Calculator",        grades:"Gr 5–12", subject:"Math",    color:"#006a96",
   desc:"The world's best graphing calculator. No login, instant graphing.",
   url:"https://www.desmos.com/calculator",
   embed:true},
  {id:"desmos-geometry",    cat:"Desmos",        emoji:"🔺", label:"Desmos Geometry",          grades:"Gr 5–10", subject:"Math",    color:"#006a96",
   desc:"Construct geometric figures and explore relationships.",
   url:"https://www.desmos.com/geometry",
   embed:true},
  // ── Scratch (MIT — project embeds) ────────────────────────────────────────
  {id:"scratch-math",       cat:"Scratch · MIT", emoji:"🐱", label:"Math Quiz Game",           grades:"Gr 2–5",  subject:"CS+Math", color:"#ff8c1a",
   desc:"Interactive math quiz built in Scratch. Practice arithmetic in a game.",
   url:"https://scratch.mit.edu/projects/10128407/embed",
   embed:true, github:"https://github.com/LLK/scratch-gui"},
  {id:"scratch-platformer",cat:"Scratch · MIT",  emoji:"🎮", label:"Platformer Starter",       grades:"Gr 3–8",  subject:"CS",      color:"#ff8c1a",
   desc:"Modify a platformer game to learn sequencing, loops and events.",
   url:"https://scratch.mit.edu/projects/107663264/embed",
   embed:true},
  // ── Khan Academy Exercises (link-out — iframe blocked by KA) ──────────────
  {id:"khan-math",          cat:"Khan Academy",  emoji:"📐", label:"Khan Math Exercises",      grades:"K–12",    subject:"Math",    color:"#14bf96",
   desc:"Adaptive K-12 math. Opens in a new tab (Khan blocks embedding).",
   url:"https://www.khanacademy.org/math",
   embed:false},
  {id:"khan-cs",            cat:"Khan Academy",  emoji:"💻", label:"Khan Computing",           grades:"Gr 4–12", subject:"CS",      color:"#14bf96",
   desc:"JavaScript, HTML/CSS, SQL courses. Opens in new tab.",
   url:"https://www.khanacademy.org/computing",
   embed:false},
  // ── Code.org ──────────────────────────────────────────────────────────────
  {id:"codeorg-frozen",     cat:"Code.org",      emoji:"❄️", label:"Frozen Hour of Code",      grades:"Gr 2–6",  subject:"CS",      color:"#00adcc",
   desc:"Code with Elsa and Anna using drag-and-drop block coding.",
   url:"https://studio.code.org/hoc/1",
   embed:true},
  {id:"codeorg-minecraft",  cat:"Code.org",      emoji:"⛏️", label:"Minecraft Hour of Code",   grades:"Gr 3–8",  subject:"CS",      color:"#00adcc",
   desc:"Mine and craft with code. Intro to loops and conditionals.",
   url:"https://studio.code.org/s/mc/lessons/1/levels/1",
   embed:true},

  // ── Elementary Reading + Phonics (Starfall — freely embeddable) ───────────
  {id:"starfall-abc",       cat:"Starfall",      emoji:"🔤", label:"Starfall ABCs",            grades:"Pre-K–K", subject:"Phonics",  color:"#ff6b9d",
   desc:"Animated letter-sound pairs. Tap letters to hear sounds and see words. Perfect for early readers.",
   url:"https://www.starfall.com/h/abcs/",
   embed:true},
  {id:"starfall-learn",     cat:"Starfall",      emoji:"📚", label:"Starfall Learn to Read",   grades:"K–1",     subject:"Reading",  color:"#ff6b9d",
   desc:"Step-by-step phonics stories. Children read along with animation at their own pace.",
   url:"https://www.starfall.com/h/learn-to-read/",
   embed:true},

  // ── Elementary Math Games (embeddable) ────────────────────────────────────
  {id:"mathplay-tables",    cat:"Math Playground",emoji:"🏃",label:"Math Games",               grades:"Gr 1–6",  subject:"Math",    color:"#e74c3c",
   desc:"100+ free math games covering addition, multiplication, fractions, geometry and more.",
   url:"https://www.mathplayground.com/",
   embed:true},
  {id:"arcademics-typing",  cat:"Arcademics",    emoji:"🏎️", label:"Math Racing Games",        grades:"Gr 1–6",  subject:"Math",    color:"#e74c3c",
   desc:"Multiplayer math racing games. Practice facts through friendly competition.",
   url:"https://www.arcademics.com/games/grand-prix",
   embed:true},
  {id:"funbrain-math",      cat:"Funbrain",      emoji:"🧮", label:"Math Baseball",            grades:"Gr 1–4",  subject:"Math",    color:"#ff8c1a",
   desc:"Answer math problems to hit singles, doubles, and home runs. Covers all four operations.",
   url:"https://www.funbrain.com/games/math-baseball",
   embed:true},

  // ── Music Interactive (Chrome Music Lab — Google, freely embeddable) ───────
  {id:"music-lab-song",     cat:"Chrome Music Lab",emoji:"🎹",label:"Song Maker",              grades:"K–8",     subject:"Music",   color:"#0a7c8a",
   desc:"Create melodies using colorful bars. No music knowledge needed — just tap and listen.",
   url:"https://musiclab.chromeexperiments.com/Song-Maker/",
   embed:true, github:"https://github.com/googlecreativelab/chrome-music-lab"},
  {id:"music-lab-rhythm",   cat:"Chrome Music Lab",emoji:"🥁",label:"Rhythm",                 grades:"K–5",     subject:"Music",   color:"#0a7c8a",
   desc:"Tap out rhythms and see them visualized. Learn beats and patterns through play.",
   url:"https://musiclab.chromeexperiments.com/Rhythm/",
   embed:true, github:"https://github.com/googlecreativelab/chrome-music-lab"},
  {id:"music-lab-spectrogram",cat:"Chrome Music Lab",emoji:"🌊",label:"Spectrogram",          grades:"Gr 3–8",  subject:"Music+Science",color:"#0a7c8a",
   desc:"See sounds as they happen. Explore how different instruments and voices look as waves.",
   url:"https://musiclab.chromeexperiments.com/Spectrogram/",
   embed:true, github:"https://github.com/googlecreativelab/chrome-music-lab"},

  // ── More PhET (elementary-appropriate) ────────────────────────────────────
  {id:"phet-counting",      cat:"PhET · Math",   emoji:"🔢", label:"Number Play",             grades:"Pre-K–2", subject:"Math",    color:"#e05c3a",
   desc:"Count objects, make groups, explore tens and ones. Perfect for early math learners.",
   url:"https://phet.colorado.edu/sims/html/number-play/latest/number-play_all.html",
   embed:true, github:"https://github.com/phetsims/number-play"},
  {id:"phet-compare",       cat:"PhET · Math",   emoji:"⚖️", label:"Number Compare",          grades:"Pre-K–1", subject:"Math",    color:"#e05c3a",
   desc:"Compare groups of objects to build greater-than, less-than understanding.",
   url:"https://phet.colorado.edu/sims/html/number-compare/latest/number-compare_all.html",
   embed:true, github:"https://github.com/phetsims/number-compare"},
  {id:"phet-states",        cat:"PhET · Science",emoji:"🧊", label:"States of Matter",        grades:"Gr 3–8",  subject:"Science", color:"#2d6ea8",
   desc:"Heat and cool matter to see solids, liquids, and gases change states.",
   url:"https://phet.colorado.edu/sims/html/states-of-matter-basics/latest/states-of-matter-basics_all.html",
   embed:true, github:"https://github.com/phetsims/states-of-matter-basics"},
  {id:"phet-color-vision",  cat:"PhET · Science",emoji:"🌈", label:"Color Vision",            grades:"Gr 2–6",  subject:"Science", color:"#2d6ea8",
   desc:"Explore how light makes color. Mix red, green, and blue light to make any color.",
   url:"https://phet.colorado.edu/sims/html/color-vision/latest/color-vision_all.html",
   embed:true, github:"https://github.com/phetsims/color-vision"},

  // ── Typing + Keyboard Skills ───────────────────────────────────────────────
  {id:"typing-club",        cat:"TypingClub",    emoji:"⌨️", label:"Learn to Type",           grades:"Gr 2–8",  subject:"Keyboard", color:"#2c3e50",
   desc:"The most popular free typing program. 600+ lessons from home row to full keyboard.",
   url:"https://www.typingclub.com/sportal/program-3.game",
   embed:true},

  // ── Art + Design (Mondrian style generators — no login needed) ────────────
  {id:"art-mondrian",       cat:"Art Generator", emoji:"🟦", label:"Mondrian Art Maker",      grades:"Pre-K–8", subject:"Arts",    color:"#d4a012",
   desc:"Create geometric abstract art in the style of Piet Mondrian. Explore color and composition.",
   url:"https://www.kennedycentereducation.org/education-resources/classroom-resources/mondrian-creator",
   embed:false},

  // ── World Languages (Digital Dialects — embeddable games) ─────────────────
  {id:"digitalect-spanish", cat:"Digital Dialects",emoji:"🇪🇸",label:"Spanish Games",        grades:"K–6",     subject:"Spanish", color:"#c0392b",
   desc:"Fun browser games for learning Spanish numbers, colors, animals, body parts and more.",
   url:"https://www.digitaldialects.com/Spanish.htm",
   embed:true},
  {id:"digitalect-french",  cat:"Digital Dialects",emoji:"🇫🇷",label:"French Games",         grades:"K–6",     subject:"French",  color:"#002395",
   desc:"Interactive French vocabulary games. Numbers, food, family, and daily life.",
   url:"https://www.digitaldialects.com/French.htm",
   embed:true},

  // ── iCivics (civics + history — freely embeddable) ────────────────────────
  {id:"icivics-do-i-have",  cat:"iCivics",       emoji:"🏛️", label:"Do I Have a Right?",     grades:"Gr 5–8",  subject:"Civics",  color:"#1a5276",
   desc:"Run a law firm defending constitutional rights. Award-winning civics game.",
   url:"https://www.icivics.org/games/do-i-have-right",
   embed:false},

  // ── National Geographic Kids (science + geography) ─────────────────────────
  {id:"natgeo-kids",        cat:"Nat Geo Kids",  emoji:"🦁", label:"Nat Geo Animal Games",   grades:"K–5",     subject:"Science", color:"#ffcd00",
   desc:"Interactive animal quizzes, habitat maps, and wildlife videos from National Geographic.",
   url:"https://kids.nationalgeographic.com/games/",
   embed:true},
];


export const CA_CITIES=["Anaheim","Bakersfield","Berkeley","Chico","Fresno","Hayward","Irvine","Long Beach","Los Angeles","Marin County","Modesto","Napa","Oakland","Ontario","Palo Alto","Pasadena","Riverside","Sacramento","Salinas","San Diego","San Francisco","San Jose","Santa Ana","Santa Barbara","Santa Clara","Santa Cruz","Santa Rosa","Stockton","Sunnyvale","Ventura","Other"];
export const GRADES=["Pre-K","Kindergarten","1st Grade","2nd Grade","3rd Grade","4th Grade","5th Grade","6th Grade","7th Grade","8th Grade","9th Grade","10th Grade","11th Grade","12th Grade"];
export const SITUS=["Homeschool","Public School","Charter School","Accredited Private School","Non-Accredited Private School","Not Currently Enrolled"];
export const GOALS=["🤖 AI-powered learning","⚡ 2-hour academic block","🌿 Outdoor & projects","🎨 Arts & creativity","🔬 STEM & science","🌍 Language learning","📖 Reading & literacy","🎯 Small group coaching","💡 Self-directed","🏆 Ahead of grade level","❤️ Social-emotional","🎵 Music"];
